### ISSUE TITLE
[http] URL encoding

### ISSUE THREAD

**Issue by moodyblue** [openhab/openhab-addons#11920]
## Expected Behavior
Sometimes it's necessary to assign values containning national characters to string items (and this works ok). The problem is that http binding is not URL encoding such characters, therefore linking them in string channels results in errors such as
```
2021-12-31 17:00:03.013 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'https://api.telegram.org/bot****/sendMessage?chat_id=*****&text=The%20following%20batteries%20need%20to%20be%20replaced:%20[Interruptor%20Portão%20Garagem:%2016.0%25]' (method='GET', content='null') failed: 400 Bad Request
```
In above message the national character `ã` should have been encoded by the binding. In fact, if `a` was used instead of `ã` the message is sent.

## Current Behavior
Errors are produced in `openhab.log` when national characters are assigned to string channels.

## Steps to Reproduce (for Bugs)
Create a thing as follows:
```
UID: http:url:d52db6a46a
label: $Telegram
thingTypeUID: http:url
configuration:
  authMode: BASIC
  ignoreSSLErrors: false
  baseURL: https://api.telegram.org/bot***************************************
  delay: 0
  stateMethod: GET
  refresh: 30
  commandMethod: GET
  contentType: text/plain
  timeout: 3000
  bufferSize: 2048
channels:
  - id: message
    channelTypeUID: http:string
    label: Message
    description: ""
    configuration:
      mode: WRITEONLY
      commandExtension: /sendMessage?chat_id=*********&text=%2$s
```

1. Link the `message` to a string item
2. Assign a value to the string item not containning national characters -> no errors in log
3. Assign a value to the string item containning national characters -> errors in log

## Context
I am using the http binding for multiple purposes. In above case I'm using it instead of the telegram binding (I don't need to poll received messages, I only need to send occasional alerts and http binding is perfect for that).

## Your Environment
* Version used: 3.2.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): QNAP NAS
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): QTS 5, Java11 (Zulu)
