### ISSUE TITLE
 [shelly] Button 1 not work

### ISSUE THREAD

**Issue by kristoferus75** [openhab/openhab-addons#11940]
Hi !
I use shelly button 1 and have already opened an issue on 
my rule doesnt work

https://community.openhab.org/t/shelly-button-1-rule-doesnt-work-openhab3/130986

my shelly Button have a fixed ip address

**on shelly button 1 Webinterface:**

Enable CoIoT
and
CoIoT peer: 192.168.77.15:5683
192.168.77.15 is my openhab server

**obenhab3.2**

What i did is → add Bindng Shelly
add thing → Shelly Button 1 (SHBTN-1)
add in Model → add Eqipment from Things
and there are 5 items → i choose all and add

Battery Level (Measurement Energy)
Event (Point)
Input (Point)
Low Battery (LowBattery Energy)
Signal Strengh

shelly button thing on openhab is online

**Rule**

```
configuration: {}
triggers:
  - id: "1"
    configuration:
      itemName: ShellyButton1SHBTN1_Event
      command: S
    type: core.ItemCommandTrigger
conditions:
  - inputs: {}
    id: "3"
    configuration:
      itemName: Zwischenstecker01_ON_OFF_PLUG_IN_UNITSwitch
      state: ON
      operator: =
    type: core.ItemStateCondition
actions:
  - inputs: {}
    id: "2"
    configuration:
      command: OFF
      itemName: Zwischenstecker01_ON_OFF_PLUG_IN_UNITSwitch
    type: core.ItemCommandAction
```
wtih **tcpdump** on openhab server i see it of i press the button:

`16:58:01.475429 IP 192.168.5.144.5683 > 192.168.77.15.5683: UDP, length 145`

**log file on openhab server**

```
`2021-12-31
 17:12:31.119 [INFO ] [openhab.event.ChannelTriggeredEvent ] - 
shelly:shellybutton1:b107659ff4:status#button triggered 
SHORT_PRESSED2021-12-31 17:12:31.120 [INFO ] 
[openhab.event.ItemStateChangedEvent ] - Item 
'ShellyButton1SHBTN1_EventCount' changed from 67 to 68`
```

## Expected Behavior
i have added an rule but trigger does never executed 
rule should work

## Current Behavior
if i press the button on shelly -> short -> nothing happens

## Context
cannot use the shelly button

## Your Environment
debian bullseye
openhab3.2.0
shelly button Current version: 20211109-125924/v1.11.7-g682a0db
