### ISSUE TITLE
[jsscripting]  Access to the same script at the same time causes exception

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-addons#12025]
## Expected Behavior

When I schedule a timer it should execute whether the script that spawned it is running or not, or whether another timer spawned by that script is running or not. 

## Current Behavior

1. If a timer is created and expires while the script that spawned it is running a "Multi threaded access" exception is thrown.
2. If two timers created by a given script try to execute at the same time a "Multi threaded access" exception is thrown.

## Possible Solution

Extend synchronization to timers. However I don't think that will solve it in all cases. For example, timers that interact with each other or with themselves.

## Steps to Reproduce (for Bugs)

Script running:
1. Create a timer to go off in the near future
2. Create a busy wait loop that blocks the script from exiting until after the timer's expiration

Multiple timers:
1. Create a ZonedDateTime for the near future.
2. Create two timers using the date time from 1.

Other
1. Create a timer and in the lambda for that timer try to cancel that timer.

```
var timer = null;
timer = actions.ScriptExecution.createTimer(time.ZonedDateTime.now().plusSeconds(1), () => { timer.cancel(); });
```

## Context

Personally, I'm trying to create tests for a library that manages timers. I need to create a timer, wait a bit and then check that something happened (or didn't happen). Depending on the timing the sometimes timers collide.

Beyond that, periodically and randomly users in general will experience inexplicable exceptions when the timing works out just right that a script is running when a timer triggers, or two timers from the same script execute at the same time. This is why I file this as a bug instead of a feature request.

## Your Environment

```
runtimeInfo:
  version: 3.3.0
  buildString: "Build #2687"
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA
  osName: Linux
  osVersion: 5.4.0-92-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 133896488
  totalMemory: 502267904
bindings:
  - astro
  - bluetooth
  - chromecast
  - ipcamera
  - mail
  - mqtt
  - network
  - networkupstools
  - openweathermap
  - roku
  - shelly
  - zigbee
  - zwave
```
