### ISSUE TITLE
[wled] Implement more nightlight (sleep) features

### ISSUE THREAD

**Issue by digitlength** [openhab/openhab-addons#12109]
Currently the WLED binding provides a Switch Channel in order to turn the nighlight feature on and off.

This is a request to add the following Channels:

- NUMBER: Duration of nightlight in minutes (JSON API `nl.dur`)
- NUMBER: Nightlight mode (JSON API `nl.mode`)
- NUMBER: Target brightness of nightlight feature (JSON API `nl.tbri`)

This would allow a user to use openHAB to switch the nighlight modes and timings throughout the day. For example:

- In the morning, set the mode to 1 (FADE), set duration to 15 minutes, and target brightness to 255, then flick the nightlight switch on: fade up the lights from already off to 255 in 15 minutes.
- In the evening, set the mode to 1 (FADE), set duration to 60 minutes, and the target brightness to 0, then flick the nightlight switch on: fade the already on lights down from 255 to 0.

I have currently implemented the above using MQTT and Jython functions in order to control lights in the kids room - slow-ish wakeup, and gradual darkening. But I'd prefer to move to using the binding...

## Your Environment

```yaml
runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA
  osName: Linux
  osVersion: 5.11.22-5-pve
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 333990936
  totalMemory: 778043392
```
