### ISSUE TITLE
[Telegram] sendTelegramQuery: Query not sent after "long pause"

### ISSUE THREAD

**Issue by SHU-red** [openhab/openhab-addons#12753]
## Expected Behavior

- Im executing a rule for each day at 9am to check if my vacuum robot has to clean
- After 3 Days, i should get a query for asking me to vacuum

## Current Behavior

- For some reason everything is executed as it should (that means the whole code before and after), but no telegram-message is sent and frontail does not show error messages
- If i then change the script for testing purpose to the current time plus some minutes it gets executed properly
- This gives me "the feeling" that the query is only not sent if there was a long duration before, where no message has been sent
- I already tested it with specifying and with not specifying a specific ChatID (as in the code example below) --> same behavior

I hope there is no error on my side, but the fact that exactly this code is working after i re-set the time value for testing purposes tells me that i did not make errors in coding ... hopefully

## Steps to Reproduce (for Bugs)

1. Do nothing and wait for the rule to execute in 3 days at 9am

## Context

```
rule "Check for cleaning request"
when
Time cron "0 0 9 * * ?"
then
logInfo("VACUUM", "CHECK FOR CLEANING REQUEST")

// if exactly three days are gone
if (dVac1_last_clean_days.state == 3){

    // notification
    val telegramAction = getActions("telegram","telegram:telegramBot:mybot)
    telegramAction.sendTelegramQuery("<b> &#129529; Shall i clean up? &#129529; </b>\n\nLast time was " + dVac1_last_clean_days.state.toString + " days ago!","oh_esme_sweep","Sweep","No Action")


    // Specified with chatID but same result as without
    // telegramAction.sendTelegramQuery(-123456789L,"<b> &#129529; Shall i clean up? &#129529; </b>\n\nLast time was " + dVac1_last_clean_days.state.toString + " days ago!","oh_esme_sweep","Sweep","No Action"

    // Other code getting executed properly
    
    logInfo("VACUUM", "CLEANING REQUEST ADDED TO LOGLIST")
}

end

```

## Your Environment

* Version used: openHAB 3.2.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Docker: "openhab/openhab:latest-alpine"
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): TrueNAS Scale
```

runtimeInfo:
  version: 3.2.0
  buildString: Release Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.13
  javaVendor: Alpine
  osName: Linux
  osVersion: 5.10.109+truenas
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 98751320
  totalMemory: 310378496
bindings:
  - astro
  - chromecast
  - http
  - ipcamera
  - miio
  - mqtt
  - network
  - ntp
  - openweathermap
  - pushbullet
  - somfytahoma
  - telegram
  - wifiled
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/100.0.4896.162 Safari/537.36
timestamp: 2022-05-16T17:54:40.685Z

```
