### ISSUE TITLE
[tado] Air Conditioning: Thing values not updating

### ISSUE THREAD

**Issue by dandjo** [openhab/openhab-addons#13252]
I have a Tado Smart AC Control in my house which is properly working.

## Expected Behavior
The states/values in the Things get updated from the subscribed Channels. When I set a trigger on HVAC, the AC Control does it's stuff and I would expect the power state of the Things to change. I would also expect a change after a timer expires and the AC turns off.

## Current Behavior
After setting up the Bridge, Channels and Things, the values are initially updated, but then no longer until a restart. After the restart, the values are fetched once again. Triggers do not affect other Channels, they are not updated.

## Steps to Reproduce (for Bugs)
1. Setup a "Tado Home" Thing
2. Setup a "Tado Air Condition" Thing with "Tado Home" as Bridge and Zone-Id=2
3. Setup a Thing for e.g. temperature directly from the Channel
4. Watch for channel inputs or trigger HVAC state

## Your Environment
* Version used: openHAB 3.3.0
* Hardware: RaspberryPi 4 8GB with PoE+ Hat
* Operating System and version: Ubuntu 22.04 Server for RasPi
* Other bindings installed: MQTT Broker, Netatmo

Is the issue related to this community post?
https://community.openhab.org/t/several-items-from-different-bindings-stop-updating-after-a-while/47863

Here's a screenshot of my Overview page.

![image](https://user-images.githubusercontent.com/34278179/184362780-a45397c0-dd61-498a-a933-2bc341fa13b7.png)

**Comment by dandjo** [comment]
I see the following errors in the log.

[events.log](https://github.com/openhab/openhab-addons/files/9316847/events.log)

**Comment by andrewfg** [comment]
@dandjo can you please be fully explicit on what version of OH you are running, respectively Stable/Milestone/Snapshot version?

**Comment by andrewfg** [comment]
> I see the following errors in the log.

@dandjo I can see from your log that the Tado server response contains a null value for the zone temperature; and this is causing an NPE in the binding; however it is not clear if the null response was a) actually sent by the Tado server, or b) caused by some king of network error. => Can you please turn on TRACE logging and post the respective log file?

**Comment by andrewfg** [comment]
> Is the issue related to this community post?

Not really. Although one of the old logs in that thread does happen to capture the same Tado binding error due to a null room temperature value being returned from the Tado server.

**Comment by dandjo** [comment]
> @dandjo can you please be fully explicit on what version of OH you are running, respectively Stable/Milestone/Snapshot version?

Sure.

```
runtimeInfo:
  version: 3.3.0
  buildString: Release Build
locale: en-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.16
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 5.15.0-1013-raspi
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 43316256
  totalMemory: 223346688
  startLevel: 100
bindings:
  - mqtt
  - netatmo
  - tado
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-AT
    languages:
      - de-AT
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/104.0.0.0 Safari/537.36
timestamp: 2022-08-12T18:45:43.955Z
```
