### ISSUE TITLE
[rrd4j] Could not create rrd4j database file

### ISSUE THREAD

**Issue by dandjo** [openhab/openhab-addons#13297]
When using RRD4j as persistence service i constantly get the following error when setting up a MQTT Item with the setup described below.

`[ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file 
 /var/lib/openhab/persistence/rrd4j/mqtt_testung_item.rrd': null`

1. Install a MQTT broker (Mosquitto)
2. Install and configure the MQTT broker bridge (no special configuration)
3. Configure a MQTT Thing with bridge from above
4. Add a channel with identifier `mqtt_testung_channel` with state- and command-topic `mqtt_testung_topic` and `Wh` as measurement unit
5. Link and add an Item `mqtt_testung_item` with type `Number:Energy`, semantic class `Measurement` and semantic property `Energy` (I assume that those details are not very relevant)
6. Add a rule with name `mqtt_testung_rule` with a trigger of your choice (one that gets updated frequently) and a script as follows (note that `smartpi_ptot` is also my trigger state)
![image](https://user-images.githubusercontent.com/34278179/184555861-36cf71e6-6602-4d73-ae62-32d98e186c87.png)
DSL: `events.sendCommand('mqtt_testung_item', itemRegistry.getItem('smartpi_ptot').getState());`

When removing the rule, the error is gone in the openhab log. I'm not sure if this is because no command is posted anymore or if this is for other reasons.

System environment:
```
runtimeInfo:
  version: 3.3.0
  buildString: Release Build
locale: en-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.16
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 5.15.0-1013-raspi
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 145644896
  totalMemory: 223346688
  startLevel: 100
bindings:
  - mqtt
  - netatmo
  - tado
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-AT
    languages:
      - de-AT
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/104.0.0.0 Safari/537.36
timestamp: 2022-08-14T22:20:49.075Z
```
