### ISSUE TITLE
[mqtt] REGEX Filter seems to not work in text based configurations, in UI based ones it does.

### ISSUE THREAD

**Issue by zaphood1967** [openhab/openhab-addons#13346]
When using REGEX Statements with the MQTT Binding in OH 3.3 to filter messages with Arrays, the REGEX statement only works correct when defining the Thing via UI. When defining a Thing via textfile, no message is passed at all, despite the fiter REGEX espression looks identical to the one defined in the UI.

## Expected Behavior
When using REGEX Filters on MQTT Things which have been based on textual configurations, messages that match the REGEX filter should get passed through.

## Current Behavior
Only on MQTT Things defined via UI the REGEX filter works as espected. Text based MQTT things don't pass messages at all. 

I am using a MQTT Smartmeter Device that reads the power consumption from the grid. Unfortunately, the meter does provide only a single value per packet, still they are all using the same format:

```yaml
{"Time":"2022-08-29T18:44:01","Z1":{"76_7_0":-4.04}}

```
The value after Z1 changes, so 76_7_0 could be 1_8_1 or 2_8_0 f.e., hence I needed to implement the REGEX function. 

Now, when defining the MQTT Thing in a text file, the expression looks like that: 

```csv
Thing topic Zaehler @ "MQTT" {
    Channels:
        Type number : z1Zaehlerstand       "Zählerstand"                [stateTopic="tele/Zaehler/SENSOR", transformationPattern="REGEX:(.*1_8_0.*)∩JSONPATH:$.Z1.1_8_0"] 
        Type number : z1BezugTarif1        "Bezug Tarif 1"              [stateTopic="tele/Zaehler/SENSOR", transformationPattern="REGEX:(.*1_8_1.*)∩JSONPATH:$.Z1.1_8_1"]
        Type number : z1BezugTarif2        "Bezug Tarif 2"              [stateTopic="tele/Zaehler/SENSOR", transformationPattern="REGEX:(.*1_8_2.*)∩JSONPATH:$.Z1.1_8_2"]
        Type number : z1Einspeisung        "Einspeisung"                [stateTopic="tele/Zaehler/SENSOR", transformationPattern="REGEX:(.*2_8_0.*)∩JSONPATH:$.Z1.2_8_0"]        
        Type number : z1Leistung           "Aktuelle Gesamtleistung"    [stateTopic="tele/Zaehler/SENSOR", transformationPattern="REGEX:(.*16_7_0.*)∩JSONPATH:$.Z1.16_7_0"]        
        Type number : z1LeistungL1         "Aktuelle Leistung L1"       [stateTopic="tele/Zaehler/SENSOR", transformationPattern="REGEX:(.*36_7_0.*)∩JSONPATH:$.Z1.36_7_0"]        
        Type number : z1LeistungL2         "Aktuelle Leistung L2"       [stateTopic="tele/Zaehler/SENSOR", transformationPattern="REGEX:(.*56_7_0.*)∩JSONPATH:$.Z1.56_7_0"]        
        Type number : z1LeistungL3         "Aktuelle Leistung L3"       [stateTopic="tele/Zaehler/SENSOR", transformationPattern="REGEX:(.*76_7_0.*)∩JSONPATH:$.Z1.76_7_0"]        
    }
```

Without the REGEX, the well know error is to be seen in the logs. With the REGEX, ALL outcome is filtered and no packed is passed through at all. 

So I defined the things in the UI, using the same parameters: 

```yaml
UID: mqtt:topic:6296256670:Zaehler
label: Generic MQTT Thing
thingTypeUID: mqtt:topic
configuration: {}
bridgeUID: mqtt:broker:jarvis
channels:
  - id: z1Leistung
    channelTypeUID: mqtt:number
    label: Einspeisung / Bezug (Zähler)
    description: ""
    configuration:
      stateTopic: tele/Zaehler/SENSOR
      transformationPattern: REGEX:(.*16_7_0.*)∩JSONPATH:$.Z1.16_7_0
      unit: W
  - id: z1Zaehlerstand
    channelTypeUID: mqtt:number
    label: Zählerstand
    description: ""
    configuration:
      stateTopic: tele/Zaehler/SENSOR
      transformationPattern: REGEX:(.*1_8_0.*)∩JSONPATH:$.Z1.1_8_0
      unit: Wh
  - id: z1Einspeisung
    channelTypeUID: mqtt:number
    label: Einspeisung
    description: ""
    configuration:
      stateTopic: tele/Zaehler/SENSOR
      transformationPattern: REGEX:(.*2_8_0.*)∩JSONPATH:$.Z1.2_8_0
      unit: Wh
```
Which worked like a charm. 

## Steps to Reproduce (for Bugs)
Generate a MQTT Thing via text config and apply REGEX filters. Check outcome, most probably there will be no messages geting through. Do the same again, but this time define the Thing via UI. Should now pass messages that match the REGEX  expression. 

## Context
Now, call me old fashioned, but I would like to stay with the text files as they are more easy to work with for me. Backup and Migration are more easy as well. According to the documentation, this should work.  

## Your Environment
Openhab 3.3 as VM, based on Debian and Openhabian-Script, running on Proxmox.
