### ISSUE TITLE
[bluetooth.govee] Unstable connection / sporadic or no updates

### ISSUE THREAD

**Issue by dhilgarth** [openhab/openhab-addons#13422]
## Expected Behavior
The connection to the Govee device should be stable.
Stable meaning:
- It shouldn't switch between ONLINE, OFFLINE (COMMUNICATION_ERROR) and OFFLINE without apparent reason.
- When connected, it should update the channels in the configured interval

## Current Behavior
Connection is unstable. With the device right next to the RPi, it switches between ONLINE, OFFLINE (COMMUNICATION_ERROR) and OFFLINE. But even when ONLINE, it doesn't realiably update the values
My log:
![image](https://user-images.githubusercontent.com/1180105/191315669-0c6eba03-02fe-4722-84d7-ac1ec874a938.png)

It's now 18:40, so 16 minutes after the yellow WARN entry in the log. It came ONLINE on 18:18, so it didn't update the channels even once in that 22 minutes, although it is set to update every minute.
Whenever the state switched to UNKNOWN, I edited and saved the Thing.
Also, more issue reports in the Community: https://community.openhab.org/t/govee-bluetooth-binding/115543/22

## Steps to Reproduce (for Bugs)
For me: Just add a Govee H5075 and check the logs where it's obvious that it's unreliable

## Context
I'm trying to get a consistent reading of my temperature and humidity to graph them and understand thermal insulation issues in my home at night.

## Your Environment
openHABian on SD card in RPi 4 2GB.
Freshly installed today according to https://www.openhab.org/download/ -> "Option 1: Flash the openHABian image to a SD card (Recommended)"
<details>
<summary>Technical Details:</summary>
<pre>
runtimeInfo:
  version: 3.3.0
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.16
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.15.61-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 28031368
  totalMemory: 154140672
  startLevel: 100
bindings:
  - bluetooth
  - homematic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 14
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 1600
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/105.0.0.0 Safari/537.36
timestamp: 2022-09-20T16:47:49.234Z
</pre>
</details>

My config:
Bluetooth interface Thing:
```
UID: bluetooth:bluez:hci0
label: Bluetooth Interface openhabian
thingTypeUID: bluetooth:bluez
configuration:
  backgroundDiscovery: false
  inactiveDeviceCleanupThreshold: 300
  address: E4:5F:01:D5:5D:23
  inactiveDeviceCleanupInterval: 60
```
Govee Hygrometer Thing:
```
UID: bluetooth:goveeHygrometerMonitor:hci0:a4c13865b28e
label: Govee Temperature Humidity Monitor (Pool)
thingTypeUID: bluetooth:goveeHygrometerMonitor
configuration:
  temperatureWarningMax: 0
  humidityWarningMax: 0
  address: A4:C1:38:65:B2:8E
  humidityWarningMin: 0
  refreshInterval: 60
  temperatureWarningMin: 0
  temperatureWarningAlarm: false
  humidityWarningAlarm: false
bridgeUID: bluetooth:bluez:hci0

```
