### ISSUE TITLE
[heos] Login does not work due to incorrect credential handling

### ISSUE THREAD

**Issue by 1358** [openhab/openhab-addons#13445]
The HEOS-Binding asks for the account credentials in order to access the service:
 - `username`
 - `password`

The generated code is:
```
UID: heos:bridge:<id>
label: HEOS Bridge
thingTypeUID: heos:bridge
configuration:
  ipAddress: <ip>
  username: <mailaddress>
  heartbeat: 60
  password: <password>
```

This does not work.

According to the CLI-Reference the username has to be provided in `un`, the password in `pw`.

Changing the generated code to
```
UID: heos:bridge:<id>
label: HEOS Bridge
thingTypeUID: heos:bridge
configuration:
  ipAddress: <ip>
  un: <mailaddress>
  heartbeat: 60
  pw: <password>
``` 
brings the binding to live.
