### ISSUE TITLE
[androiddebugbridge] IllegalStateException raised from time to time

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-addons#13722]
I have a globally working setup but from time to time I see this error in openhab.log : 

```
2022-11-15 02:22:00.068 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.IllegalStateException: connect() must be called first
	at com.tananaev.adblib.AdbConnection.open(AdbConnection.java:321) ~[?:?]
	at org.openhab.binding.androiddebugbridge.internal.AndroidDebugBridgeDevice.lambda$5(AndroidDebugBridgeDevice.java:733) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

This does not seem to affect global functioning of the binding and I have not been able to identify circumstancies of it.

```
runtimeInfo:
  version: 3.4.0
  buildString: "Build #3158"
locale: fr-FR
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.15
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.56+19-CA
  osName: Linux
  osVersion: 5.15.0-52-generic
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 415403960
  totalMemory: 950009856
  startLevel: 100
bindings:
  - airquality
  - amazonechocontrol
  - androiddebugbridge
  - astro
  - freeboxos
  - gce
  - icalendar
  - javarule
  - lgthinq
  - linky
  - logreader
  - meteoalerte
  - mqtt
  - mynice
  - netatmo
  - network
  - notificationsforfiretv
  - openuv
  - rfxcom
  - sagercaster
  - somfytahoma
  - sonos
  - synopanalyzer
  - systeminfo
  - telegram
  - tradfri
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 0.8
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: fr
    languages:
      - fr
      - fr-FR
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 2100
    height: 1313
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101
    Firefox/106.0
timestamp: 2022-11-15T08:05:18.694Z
```
