### ISSUE TITLE
Inconsistency when sending ON/OFF command to groups

### ISSUE THREAD

**Issue by TheNinth7** [openhab/openhab-addons#14100]
When sending a command to a group with Member Base Type = None, it only works if the group contains only members of type Switch. If it contains a single item of another type, it will not work. However, if Member Base Type = Switch it works even if the group contains members of other types.

Tested this with groups of type Location, an Item of type Equipment/String and items of type Equipment/Switch.

The script I used was prepared via UI with the following action:

```
actions:
  - inputs: {}
    id: "2"
    configuration:
      itemName: EG
      command: OFF
    type: core.ItemCommandAction
```
