### ISSUE TITLE
[lgwebos] TV not being discovered

### ISSUE THREAD

**Issue by mpeter50** [openhab/openhab-addons#14350]
## Expected Behavior

Pressing the "Scan" button on the `https://myinstance.lan:8443/settings/things/add/lgwebos` page should start scanning, and when completed it should show the WebOS TVs on my network.

## Current Behavior

The WebOS TVs don't appear on the `https://myinstance.lan:8443/settings/things/add/lgwebos` page after the discovery has completed, but neither in the Thing Inbox.

The only configuration file I have manually touched since installation is `userdata/etc/log4j2.xml`. Here I have set up using the stdout appender.

Other than that, regarding related configs I have modified the Network Settings (at `https://myinstance.lan:8443/settings/services/org.openhab.network`), so that the primary and broadcast address both point to the physical network to which the TVs are connected.
Until I did this change, my automatically discovered printer was in the UNKNOWN state, since then it has been in the ONLINE state. You may see this in the event.log I uploaded.

I have uploaded the 2 log files mentioned [here](https://www.openhab.org/docs/administration/logging.html#filesystem).
They are accessible [here](https://gist.github.com/mpeter50/dbfd9a6e364e85cf0d460ea3d72a0baa).
The log level is the default, except for the lgwebos and connectsdk modules. For those I have modified the log level with the below mentioned commands while running. I did not find out how to set the log level globally.

## Possible Solution

I'll omit this, as I don't know what might be the problem.

## Steps to Reproduce (for Bugs)

0. Have an LG smart TV that runs WebOS, connect it to your network
1. Install openHAB in a Docker container, use the [recommended](https://hub.docker.com/r/openhab/openhab/) docker compose file as a template
2. Start the docker compose stack
3. Install the lgwebos binding from the openHAB Distribution section (/settings/addons/binding-lgwebos)
4. Open the menu for adding a new Thing, select the lgwebos binding (/settings/things/add/lgwebos)
5. Click "Scan"
6. Observe results

## Context

I'm trying to connect my LG WebOS TVs to openHAB, so I can control them trough it. For this, I wanted to use the automatic discovery (even though I could manually add the devices to openHAB).

Discovery generally seems to be working, as the IPP Binding finds my printer.

My issue seems to be very similar to #4423, to which no solution was found. One key difference is that I use Docker for running openHAB, but since I use host networking for it, I think this should not be a problem.
Enabling trace level logs with the `log:set TRACE org.openhab.binding.lgwebos` and `log:set TRACE com.connectsdk` commands did not result in any logs printed to the console after pressing the "Scan" button.
I was running the `log:set` commands with the openhab console, which I started with the `docker exec -it openhab /openhab/runtime/bin/client` command.
I was reading the log with the `docker-compose -ft` command. The STDOUT appender has been set up for the Root and the openhab.event loggers, so that I can watch for the log messages with the `docker-compose logs -ft` command.

By running `gssdp-discover -i eth0 --timeout=3` on the same machine where openHAB runs (but outside of the container), I see the LG WebOS TVs ([here is one of them](https://gist.github.com/mpeter50/dbfd9a6e364e85cf0d460ea3d72a0baa#file-gssdp-discover-output-for-one-of-the-tvs)) that openHAB did not find, but only while they are turned on, not in standby (this is probably normal).

This is a fresh installation. If it helps, I can easily reinstall openHAB, or test snapshots if you think it might help in finding out what is the problem.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
  * openHAB: Docker image `openhab/openhab:3.4.1`, downloaded from Docker Hub
  * addons: I did not use the addon package, they were automatically downloaded by openHAB
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspbian Buster

I'm running openHAB in a Docker container, which is configured according to this docker compose configuration:
```
services:
    openhab:
        image: "openhab/openhab:3.4.1"
        restart: unless-stopped
        network_mode: host
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "addons:/openhab/addons"
            - "config:/openhab/conf"
            - "userdata:/openhab/userdata"
        environment:
            CRYPTO_POLICY: "unlimited"
            EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Budapest"
            OPENHAB_HTTP_PORT: "8080"
            OPENHAB_HTTPS_PORT: "8443"
        container_name: openhab
```
