### ISSUE TITLE
[velux] inverting position has no effect

### ISSUE THREAD

**Issue by jirikraus** [openhab/openhab-addons#14404]
## Expected Behavior
With `inverted: true` I expect that a UP command opens my Velux windows a DOWN command closed my Velux windows and that the visualization in the web front end reflects that.

## Current Behavior
When my Velux window is closed it state is reported as `0`:
```
openhab> openhab:status Lichtkuppellinks_Position
0
```
When I send an UP command the status remains unchanged. When I send a DOWN command the window opens and the status is reported as `100`
```
openhab> openhab:status Lichtkuppellinks_Position
100
```
This matches the behavior of my non inverted roller shutters. So setting `inverted: true` does not seem to have an effect.

## Steps to Reproduce (for Bugs)
Set `inverted: true`:
```
UID: velux:window:192_168_0_119:Lichtkuppel_links
label: Lichtkuppel links
thingTypeUID: velux:window
configuration:
  name: Lichtkuppel links
  inverted: true
  serial: 08:02:07:26:00:30:E0:03
bridgeUID: velux:klf200:192_168_0_119
```
Behavior remains unchanged to `inverted: false`.

## Context
Controlling Velux Windows is intuitive.

## Your Environment

I am using OpenHAB 3.4.2 from openhabian on a Raspberry Pi 3 Model B Rev 1.2
``` 
##   Release = Raspbian GNU/Linux 11 (bullseye)
##    Kernel = Linux 5.15.76-v7+
##  Platform = Raspberry Pi 3 Model B Rev 1.2
```
The Velux products are connected via KLF 200 using the SLIP protocol.
