### ISSUE TITLE
[ipcamera] `image` never updated when using ffmpeg channel in combination with `pollImage`

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#14686]
STR:

- install IPCamera binding
- configure generic thing with ffmpeg support 
- link `image` and `pollImage` channel
- set `updateImageWhen`to `1` ("Update the Image channel only when the pollImage channel is turned on.")
- send `ON` to `pollImage`
- `image` channel is not updated

One of the reasons is that `updateImageChannel` is set to `false` when `pollImage` is set to `ON`. But this alone does not fix it, at some point it just turns off again. 

```java
case CHANNEL_POLL_IMAGE:
                    if (OnOffType.ON.equals(command)) {
                        if (snapshotUri.isEmpty()) {
                            ffmpegSnapshotGeneration = true;
                            setupFfmpegFormat(FFmpegFormat.SNAPSHOT);
                            updateImageChannel = false;
                        } else {
                            updateImageChannel = true;
                            updateSnapshot();// Allows this to change Image FPS on demand
                        }
                    } else {
                        Ffmpeg localSnaps = ffmpegSnapshot;
                        if (localSnaps != null) {
                            localSnaps.stopConverting();
                            ffmpegSnapshotGeneration = false;
                        }
                        updateImageChannel = false;
                    }
                    return;
```

**Comment by Skinah** [comment]
From the readme:

pollImage | Switch | This control can be used to manually start and stop using your CPU to create snapshots from a RTSP source. If you have a snapshot URL setup in the binding, only then can this control can be used to update the Image channel.

I agree it is not 100% clear, and also a separate control should be created instead of sharing the switch if people want to do this.

1: A switch to start and stop the CPU load and network traffic of using a RTSP stream to create snapshots.
2: A switch to start and stop the image channel getting updated.

There was a memory leak of some kind occurring when an image item was updated a lot. Have not tested this in a very long time, probably before OH3 so it may be fine to update the image item once a second on a fast system, but it can flood the event bus with the raw image data and I have seen it choke a system up. Data gets sent to the event bus faster than it can get processed and logged etc...

**Comment by J-N-K** [comment]
```
UID: ipcamera:generic:95ee9d211a
label: RTSP/HTTP IP Camera
thingTypeUID: ipcamera:generic
configuration:
  mjpegOptions: -q:v 5 -r 2 -vf scale=640:-2 -update 1
  ipAddress: 192.168.0.185
  mjpegUrl: ffmpeg
  updateImageWhen: "1"
  gifPreroll: 0
  ffmpegLocation: /opt/homebrew/bin/ffmpeg
  ipWhitelist: DISABLE
  mp4OutOptions: -c:v copy -c:a copy
  pollTime: 30000
  password: <....>
  port: 80
  snapshotUrl: ffmpeg
  snapshotOptions: -an -vsync vfr -q:v 2 -update 1
  ffmpegInput: rtsp://192.168.0.185:554/stream1
  gifOutOptions: -r 2 -filter_complex
    scale=-2:360:flags=lanczos,setpts=0.5*PTS,split[o1][o2];[o1]palettegen[p];[o2]fifo[o3];[o3][p]paletteuse
  hlsOutOptions: -strict -2 -f lavfi -i aevalsrc=0 -acodec aac -vcodec copy
    -hls_flags delete_segments -hls_time 2 -hls_list_size 4
  username: <....>
```

There is a `snapshotUrl` configured, but that get's erased because it is `ffmpeg` and then it is not working at all.
