### ISSUE TITLE
[iCalendar] Public Calendar won't download since openHAB 3.4.3

### ISSUE THREAD

**Issue by feuerwasser85** [openhab/openhab-addons#14800]
## Expected Behavior
iCAL File will get downloaded. TLS Connection get's established.

## Current Behavior
Calender won't be downloaded due to TLS issues.
``[g.icalendar.internal.handler.PullJob] - Download of calendar failed with ExecutionException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target``

## Possible Solution
Implement the DigiCert Global Root G2 in the openHAB truststore if its not already there.

## Steps to Reproduce (for Bugs)
1. Create iCalendar Calendar Thing with following parameters:
```
UID: icalendar:calendar:abfuhrkalender
label: Abfuhrkalender
thingTypeUID: icalendar:calendar
configuration:
  maxSize: 16
  url: https://abfuhrtermine.awp-paf.de/WasteManagementPfaffenhofen/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=173251001&AboID=391105&Fra=P;B;S;RM
  refreshTime: 360
```
2. Click Save
3. Thing will get imediately offline. The following line can be found in the log:
`[g.icalendar.internal.handler.PullJob] - Download of calendar failed with ExecutionException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

## Context
This worked perfectly fine until openHAB 3.4.3. Restarting was not a problem. It looks like the openHAB truststore doesn't trust the DigiCert Root CA anymore. The Certificate seems valid. See https://abfuhrtermine.awp-paf.de

## Your Environment
openHAB 3.4.3 in Docker
Synology DS920+
DSM 7.1.1-42962 Update 4
Docker for Synology SPK 20.10.3-1308
