### ISSUE TITLE
[WLED] send command "DECREASE or INCREASE" to Global_Brightness not working?

### ISSUE THREAD

**Issue by niceguy0815** [openhab/openhab-addons#14832]
Hi,
i’m trying to creat a rule for a Switch to dimm my WLED Binding /Thing

on my shelly and zigbee Lights / Dimmers i can use send command “DECREASE or INCREASE” to the Brightness item to get dimmer switch working but on the
" Global Brightness" item from the WLED Thing it is not working.

I see in the log:

` Item 'Kuchenzeile_WLED_Global_Brightness' received command INCREASE`

But it did not change the Brightness.

Than i hav testet it with the " Master Controls" Item or the " Segment Brightness" Item.

And on thes Items DECREASE command sems to worke but the INCREASE command shuts the WLED OFF and there is no steps to down dimming the Brightness.

IS this a bug ore do i something wrong?

example Rule DECREASE:

```
configuration: {}
triggers:
  - id: "1"
    configuration:
      event: "5002"
      channelUID: deconz:switch:00212E05388E:54ef4410004c1384010012:buttonevent
    type: core.ChannelEventTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      itemName: Kuchenzeile_WLED_Global_Brightness
      command: DECREASE
    type: core.ItemCommandAction
```
or INCREASE:

```
configuration: {}
triggers:
  - id: "1"
    configuration:
      event: "3002"
      channelUID: deconz:switch:00212E05388E:54ef4410004c1384010012:buttonevent
    type: core.ChannelEventTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      itemName: Kuchenzeile_WLED_Global_Brightness
      command: INCREASE
    type: core.ItemCommandAction
```
