### ISSUE TITLE
[mqtt][homeassistant] Light misses channels

### ISSUE THREAD

**Issue by enboig** [openhab/openhab-addons#14856]
I am using zigbee2mqtt and my light misses switch channel.

```json
{
    "availability": [
        {
            "topic": "zigbee2mqtt/bridge/state"
        }
    ],
    "brightness": true,
    "brightness_scale": 254,
    "command_topic": "zigbee2mqtt/encimeraCuina/set",
    "device": {
        "identifiers": [
            "zigbee2mqtt_0x0c4314fffe0f8ab6"
        ],
        "manufacturer": "IKEA",
        "model": "TRADFRI driver for wireless control (30 watt) (ICPSHC24-30EU-IL-1)",
        "name": "encimeraCuina",
        "sw_version": "2.3.086"
    },
    "effect": true,
    "effect_list": [
        "blink",
        "breathe",
        "okay",
        "channel_change",
        "finish_effect",
        "stop_effect"
    ],
    "json_attributes_topic": "zigbee2mqtt/encimeraCuina",
    "name": "encimeraCuina",
    "schema": "json",
    "state_topic": "zigbee2mqtt/encimeraCuina",
    "unique_id": "0x0c4314fffe0f8ab6_light_zigbee2mqtt"
}
```

The automatic device is:
```
UID: mqtt:homeassistant_zigbee2mqtt_5F0x0c4314fffe0f8ab6:mqtt-broker:encimeraCuina
label: encimeraCuina
thingTypeUID: mqtt:homeassistant_zigbee2mqtt_5F0x0c4314fffe0f8ab6
configuration:
  topics:
    - sensor/0x0c4314fffe0f8ab6/update_state
    - sensor/0x0c4314fffe0f8ab6/power_on_behavior
    - device_automation/0x0c4314fffe0f8ab6/action_on
    - binary_sensor/0x0c4314fffe0f8ab6/update_available
    - select/0x0c4314fffe0f8ab6/power_on_behavior
    - update/0x0c4314fffe0f8ab6/update
    - sensor/0x0c4314fffe0f8ab6/linkquality
    - device_automation/0x0c4314fffe0f8ab6/action_off
    - light/0x0c4314fffe0f8ab6/light
    - select/0x0c4314fffe0f8ab6/effect
  basetopic: homeassistant
bridgeUID: mqtt:broker:mqtt-broker
```
But I don't get any switch for the light.

![Screenshot_20230420_145237](https://user-images.githubusercontent.com/1155203/233372887-f69e8a58-7d1a-4667-8949-8b2aa40aafcf.png)

After reading the documentation, I don't get why it don't work, it uses "ON"/"OFF" for state.

https://www.zigbee2mqtt.io/devices/ICPSHC24-30EU-IL-1.html

## Your Environment
* Version used: openHAB 3.3.0
* Operating System and version: Ubuntu 22.04

**Comment by enboig** [comment]
I upgraded openhab to 3.4 with the same result.

**Comment by enboig** [comment]
The problem continues after upgrading to openhab 4.0.3:

MQTT Config Topic:
```
select/0xa4c138b143374061/backlight_mode
select/0xa4c138b143374061/power_on_behavior
sensor/0xa4c138b143374061/backlight_mode
sensor/0xa4c138b143374061/linkquality
sensor/0xa4c138b143374061/power_on_behavior
switch/0xa4c138b143374061/switch
```

Code:
```
UID: mqtt:homeassistant_zigbee2mqtt_5F0xa4c138b143374061:mqtt-broker:interruptorCuina
label: interruptorCuina
thingTypeUID: mqtt:homeassistant_zigbee2mqtt_5F0xa4c138b143374061
configuration:
  topics:
    - select/0xa4c138b143374061/backlight_mode
    - select/0xa4c138b143374061/power_on_behavior
    - sensor/0xa4c138b143374061/backlight_mode
    - sensor/0xa4c138b143374061/linkquality
    - sensor/0xa4c138b143374061/power_on_behavior
    - switch/0xa4c138b143374061/switch
  basetopic: homeassistant
bridgeUID: mqtt:broker:mqtt-broker
```

But there is no switch channel, only a "Backlight mode"
