### ISSUE TITLE
[androidtv] googletv.GoogleTVMessageParser GoogleTV Error Message

### ISSUE THREAD

**Issue by MichaelHeimann** [openhab/openhab-addons#15153]
## Expected Behavior
Not Spam Logs.
Connect to shield successfully

## Current Behavior
I'm getting 11 Messages in the openhab.log every second (!) like this:

`2023-06-28 17:34:04.913 [WARN ] [tocol.googletv.GoogleTVMessageParser] - dd406711 - GoogleTV Error Message: 1a5d080312590a5708fe0412520a08534d2d4739393855120773616d73756e671801220231332a19636f6d2e676f6f676c652e616e64726f69642e766964656f73321c342e33392e3538342e3532393538383538332e372d72656c65617365`

I've reinstalled the addon from marketplace or manual via latest jar and it first shows this:

```
2023-06-28 17:34:04.776 [INFO ] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Login Successful to SHIELD
2023-06-28 17:34:04.833 [INFO ] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Message Parser Caught Exception
java.lang.ArrayIndexOutOfBoundsException: Index 124 out of bounds for length 124
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVMessageParser.handleMessage(ShieldTVMessageParser.java:132) ~[?:?]
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVConnectionManager.finishReaderMessage(ShieldTVConnectionManager.java:738) ~[?:?]
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVConnectionManager.readerThreadJob(ShieldTVConnectionManager.java:777) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

and then the spam of the error messages begins.

Also: this is from events.log:

```
2023-06-28 17:49:26.665 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'androidtv:shieldtv:dd406711' changed from OFFLINE: GoogleTV: Initializing | ShieldTV: ONLINE to OFFLINE: GoogleTV: reconnecting | ShieldTV: ONLINE
2023-06-28 17:49:26.702 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'androidtv:shieldtv:dd406711' changed from OFFLINE: GoogleTV: reconnecting | ShieldTV: ONLINE to OFFLINE: GoogleTV: Initializing | ShieldTV: ONLINE
```

## Possible Solution
ratelimit the same log message.
Fix the underlying issue would also be appreciated ;)

## Steps to Reproduce (for Bugs)
I can't say exactly. Could be a shield hardware restart I did a few days ago.

## Context
I'm trying to shutdown my tv when the shield is turned off due to CEC being incompetent. Doesn't work anymore for some days. Need to actually touch my tv-remote. duh.
Since androidtv does app autoupdates this could be due to an shield update.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
Openhab 3.4.4
org.openhab.binding.androidtv-3.2.0-4.0.0-SNAPSHOT-d1cc1c7.jar

* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
Shield Thing sais: remoteServerVersion 5.2.473254133
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
```
runtimeInfo:
  version: 3.4.4
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.19
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 5.15.0-76-generic
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 31307680
  totalMemory: 283115520
  startLevel: 100
bindings:
  - androidtv
  - deconz
  - exec
  - homeconnect
  - hue
  - lgwebos
  - minecraft
  - mqtt
  - network
  - snmp
  - wled
  - yamahamusiccast
  - yamahareceiver
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en-US
    languages:
      - en-US
      - de
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 5120
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/114.0.0.0 Safari/537.36
timestamp: 2023-06-28T15:53:25.901Z
```
