### ISSUE TITLE
[mqtt.generic] Incoming Value Transformations with not working

### ISSUE THREAD

**Issue by ronnievdc** [openhab/openhab-addons#15518]
## Expected Behavior

**Given** a payload of 
```
{
     "hcmode": {"value": "auto"},
     "flowtempdesired": {"value": 0.0},
     "hwctempdesired": {"value": 58.0},
     "hwcflowtempdesired": {"value": null},
     "disablehc": {"value": 1},
     "disablehwctapping": {"value": 0},
     "disablehwcload": {"value": 0},
     "remoteControlHcPump": {"value": 0},
     "releaseBackup": {"value": 0},
     "releaseCooling": {"value": 0}}
```

**When** configured with *Incoming Value Transformations* of `JSONPATH:$.hwctempdesired.value`
**Then** results in a Number 58.0

## Current Behavior

The `mqtt.generic` logs the following warning, resulting in an Item value of `null`
```
2023-08-29 08:34:31.383 [WARN ] [t.generic.ChannelStateTransformation] - Transformation service JSONPATH for pattern $.hwctempdesired.value not found!
2023-08-29 08:34:31.384 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '{
     "hcmode": {"value": "auto"},
     "flowtempdesired": {"value": 0.0},
     "hwctempdesired": {"value": 58.0},
     "hwcflowtempdesired": {"value": null},
     "disablehc": {"value": 1},
     "disablehwctapping": {"value": 0},
     "disablehwcload": {"value": 0},
     "remoteControlHcPump": {"value": 0},
     "releaseBackup": {"value": 0},
     "releaseCooling": {"value": 0}}' not supported by type 'NumberValue'
```

Increase logging output with the following command did not reproduce more logging
```
openhab> log:set DEBUG org.openhab.binding.mqtt.generic
```

I have also tested with *Incoming Value Transformations* of `REGEX:(.*)` but that still logs
```
2023-08-29 08:34:31.383 [WARN ] [t.generic.ChannelStateTransformation] - Transformation service REGEX for pattern (.*) not found!
```

Sample logging directly from mqtt (with `mosquitto_sub -v -t '#'`)
```
ebusd/bai/SetMode {
     "hcmode": {"value": "auto"},
     "flowtempdesired": {"value": 0.0},
     "hwctempdesired": {"value": 58.0},
     "hwcflowtempdesired": {"value": null},
     "disablehc": {"value": 1},
     "disablehwctapping": {"value": 0},
     "disablehwcload": {"value": 0},
     "remoteControlHcPump": {"value": 0},
     "releaseBackup": {"value": 0},
     "releaseCooling": {"value": 0}}
ebusd/broadcast/outsidetemp {
     "temp2": {"value": 12.824}}
```

Reading the json from `ebusd/bai/SetMode` as a type string works correctly, so the MQTT connection seems to work. Also reading the value `true` from `ebusd/global/signal` to enable/disable the Thing works fine. Only the transformations are failing.

## Possible Solution

Temporary use https://nodered.org/ to do the json transformations and send the values as numbers via a new MQTT topic.

## Steps to Reproduce (for Bugs)

Full Thing code:
```
UID: mqtt:topic:d2fa5c5a07:efe46a4077
label: MQTT for ebus
thingTypeUID: mqtt:topic
configuration:
  availabilityTopic: ebusd/global/signal
  payloadAvailable: "true"
bridgeUID: mqtt:broker:d2fa5c5a07
channels:
  - id: RoomTemperature
    channelTypeUID: mqtt:number
    label: Room Temperature
    description: ""
    configuration:
      stateTopic: ebusd/b7v/z1RoomTemp
      transformationPattern: JSONPATH:$.tempv.value
      unit: °C
  - id: OutsideTemperature
    channelTypeUID: mqtt:number
    label: Outside Temperature
    description: ""
    configuration:
      stateTopic: ebusd/broadcast/outsidetemp
      transformationPattern: JSONPATH:$.temp2.value
      unit: °C
  - id: TempOutTemporaryString
    channelTypeUID: mqtt:string
    label: ebusd/broadcast/outsidetemp
    description: ""
    configuration:
      stateTopic: ebusd/broadcast/outsidetemp
  - id: EbusSomeDebug
    channelTypeUID: mqtt:number
    label: Ebus Debug
    description: ""
    configuration:
      stateTopic: ebusd/bai/SetMode
      transformationPattern: JSONPATH:$.hwctempdesired.value
      unit: °C
```

## Context

I'm trying to read the values from our heating system.

- The heating system works connects with ebus to a specialized ebus adapter https://adapter.ebusd.eu/v5/
- The adapter connects via Wi-Fi to an ebusd daemon running in docker on the RaspberryPi4 https://github.com/john30/ebusd/wiki
- The ebusd daemon sends the message to mosquitto running in docker on the RaspberryPi4 https://github.com/john30/ebusd/wiki/3.3.-MQTT-client
- The openhab mqtt reads from the mosquitto server

## Your Environment

* Version used: Docker `openhab/openhab:4.0.2-debian`
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): 
 * `openjdk 17.0.7 2023-04-18`
 * `OpenJDK Runtime Environment (build 17.0.7+7-Debian-1deb11u1)`
 * `OpenJDK Server VM (build 17.0.7+7-Debian-1deb11u1, mixed mode, sharing)`
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): `Raspbian GNU/Linux 11 (bullseye)`

docker-compose.yml
```
version: "3.9"
services:
  openhab:
    container_name: openhab
    image: openhab/openhab:4.0.2-debian
    network_mode: host
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
     - /opt/openhab/conf:/openhab/conf
     - /opt/openhab/userdata:/openhab/userdata
     - /opt/openhab/addons:/openhab/addons
    restart: always
    environment:
      - USER_ID=999
      - GROUP_ID=994
      - CRYPTO_POLICY=unlimited
      - OPENHAB_HTTP_PORT=9080
      - OPENHAB_HTTPS_PORT=9443
```
