### ISSUE TITLE
[tradfri] IP Address overwrites to IPv6 and uninitializes Bridge

### ISSUE THREAD

**Issue by nolantern** [openhab/openhab-addons#15633]
## Expected Behavior
Type in the IP (v4) while Setup of tradfri bridge thing. This IP should stay untouched until the it's been edited by the user.

## Current Behavior
From time to time, the IP in the "Configuration" menu of the bridge changes from the entered IPv4 address to an IPv6 address. Then the bridge status changes to "COMMUNICATION ERROR" and related things and items stop working.
To workaround the bug I had to retype the IPv4 IP inside the bridge configuration and save it.

Bridge Setting:
```
UID: tradfri:gateway:xxxIDxxx
label: TRÅDFRI Gateway
thingTypeUID: tradfri:gateway
configuration:
  host: 192.168.XXX.XX
  preSharedKey: xxxKEYxxx
  port: 5684
  identity: xxxIDENTITYxxx
```

## Steps to Reproduce (for Bugs)
It happens sproadic. I did not identify any pattern.

## Your Environment
* rpi 4 8GB
* Ubuntu 20.04 LTS arm64
* Zulu Java 17
* openHAB 4.0.3
