### ISSUE TITLE
[somfytahoma] Smoke detector sensor defect state showing NULL or object reference

### ISSUE THREAD

**Issue by hypetsch** [openhab/openhab-addons#15811]
I have several Somfy smoke detectors. All of them showed `NULL` as their defect state. After reinserting the battery in one of the sensors the defect state value changed to `java.lang.Object@62e563`.  Not sure, but maybe `NULL` is shown since an openhab restart. 

![image](https://github.com/openhab/openhab-addons/assets/16302578/e3b1ca98-3825-4d49-933b-73769248faaf)

Other channels (battery states) show the correct value.

## Your Environment
```
runtimeInfo:
  version: 4.0.0.M3
  buildString: Milestone Build
locale: de-AT
systemInfo:
  javaVersion: 17.0.6
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu17.40+19-CA
  osName: Linux
  osVersion: 5.10.103-v7+
  osArchitecture: arm
  availableProcessors: 4
timestamp: 2023-10-27T07:59:01.651Z
```
