### ISSUE TITLE
[Netatmo] Only few channels are working for Presence Camera 

### ISSUE THREAD

**Issue by JuergenSmo** [openhab/openhab-addons#15883]
The Netatmo binding is workig in general, but I only have three channels populated with data. These are
- Event Timestamp
- Event Type
- Video Status
All other channels stay at null. 

## Expected Behavior
The channels should be populated with the data from the json.

## Current Behavior
The json seems to be retrieved correctly. In the TRACE log I can see:

[DEBUG] [mo.internal.handler.ApiBridgeHandler] - executeUri GET  https://api.netatmo.com/api/getevents?home_id=xxxxxxxxxxxxxx 
2023-11-12 06:30:34.126 [TRACE] [mo.internal.handler.ApiBridgeHandler] -  -returned : code [200 OK] body {"body":{"home":{"id":"xxxxxxxxxxxxxxx","events":[{"id":"xxxxxxxxxxxxxx","type":"outdoor","time":1699750919,"module_id":"xx:xx:xx:xx:xx:xx","subevents":[{"id":"xxxx-xxxx-xxxx-xxxx-xxxx","type":"animal","time":1699750919,"verified":true,"offset":0,"snapshot":{"url":"https:\/\/netatmocameraimage.blob.core.windows.net\/production\/xxxxxxxxxx?sv=2017-11-09&sr=b&se=2023-11-12T05:35:34Z&sp=r&spr=https&sig=PwFbpphlly2zCKYFD7zNdQ1dDwn0a0uDmbVbuaprIiM%3D","expires_at":1699767334},"vignette":{"url":"https:\/\/netatmocameraimage.blob.core.windows.net\/production\/xxxxxxx?sv=2017-11-09&sr=b&se=2023-11-12T05:35:34Z&sp=r&spr=https&sig=xQoXzydUHTutcR%2BAbW1CO3fkJ02sHJzRkIvteiv7ZrM%3D","expires_at":1699767334},"message":"Tier erfasst"}]
.... 

This is the same event as I can see in the Netatmo mobile phone app. I have also written a program using C/C++ for MS Windows which confirm the content of the json (of course using different Netatmo App ID).

But in the channels I only see this:
![image](https://github.com/openhab/openhab-addons/assets/95683172/24ea6092-a3b0-4343-b84a-2f3b573b7caa)
![image](https://github.com/openhab/openhab-addons/assets/95683172/19e1a3a5-e641-421e-8450-ed813ffdc06a)

## Possible Solution
This was working fine with openHab 3.3.

## Steps to Reproduce (for Bugs)
1. Install Netatmo Binding from openHab store
2. Configure the Netatmo account
3. Configure a home and use the account as bridge
4. Configure a Smart Outdoor Camera and use home as the bridge
5. Add items to the channels

## Your Environment
I am using the snapshot build 3716 of openHAB 4.1.0 on a RPi4 with 4GB running with Raspbian GNU/Linux 11 (bullseye).

**Comment by JuergenSmo** [comment]
After upgrade to 4.1.0 release build same issue. Only few channels are populated:

2023-12-24 10:11:25.024 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'HomeCam_Lastevent_Type' updated to OUTDOOR
2023-12-24 10:11:25.025 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'HomeCam_Event_Sub_Type' updated to NULL
2023-12-24 10:11:25.026 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'HomeCam_Person_ID' updated to NULL
2023-12-24 10:11:25.027 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'HomeCam_Video_Status' updated to AVAILABLE
2023-12-24 10:11:25.028 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'HomeCam_Lastevent_Message' updated to 
2023-12-24 10:11:25.031 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'HomeCam_Event_Timestamp' updated to 2023-12-24T09:59:48.000+0100
2023-12-24 10:11:25.031 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'HomeCam_Lastevent_Snapshot' updated to NULL
2023-12-24 10:11:25.032 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'HomeCam_Video_Local_URL' updated to NULL
2023-12-24 10:11:25.033 [INFO ] [openhab.event.ItemStateUpdatedEvent ] - Item 'HomeCam_Video_VPN_URL' updated to NULL

But the timestamp from the ast event is correct. And in the trace log everything is still fine.

**Comment by JuergenSmo** [comment]
Still the same on 4.1.1 release build

**Comment by multimartin** [comment]
I can confirm this in my installation - and it is super annoying, as the binding is practically useless for smoke sensor and outdoor / presence camera without these...

**Comment by clinique** [comment]
I will try to have a look at this one when possible.

**Comment by MisterBop** [comment]
Any testing support required here?

**Comment by MisterBop** [comment]
Hi, is there any workaround available until you can find some time to fix the bug? Maybe manually update code in thing web fronted? Not sure what the current root cause is

**Comment by clinique** [comment]
Can you tell me if it works with other kind of equipments (Doorbell or Welcome) ? On my side it seems to work fine but I have no functionning Presence

**Comment by MisterBop** [comment]
Dose not work with doorbell and presence. Weather station works fine.

**Comment by clinique** [comment]
Do you use a distinct security/energy homes or joined ?

**Comment by MisterBop** [comment]
Joined. But to be honest I don’t have any energy devices. The weather devices are using a separate bridge of course

**Comment by MisterBop** [comment]
Thing cofig … will past in a bit

**Comment by clinique** [comment]
> Joined. But to be honest I don’t have any energy devices. The weather devices are using a separate bridge of course 

Maybe you can give a test splitting them ?

**Comment by MisterBop** [comment]
Sure. Will do a little later. Need to take the kids to bed first.

**Comment by MisterBop** [comment]
Hi,

Test  1 approach:

1.Delete all Camera Things, Channel’s and linked items
2.Delete „home“ Thing, Channel and linked items
3. Added a new Bridge with token for cameras only
4. Authorised bridge via Web call

resoult:
New bridge could not been chosen for home Thing. Even after deletion of old bin OH. 

Test approach 2:

1. Delete all bridges 
2. Delete all Cameras etc
3. Delete all „home“ things 
4. Add old Bridge with new updated token (Weather Station and Camara only)
5. Authorise Bridge via Web Call
6. Start scann and add home and camera things
7. Add items 

Resolut: 
1. Updated bridge (token) still include energy channels?!
2. No snapshot, no other details as bevor except the once already mentioned before


Will post soon the home thing config

**Comment by MisterBop** [comment]
```
Test 
Code fence

```

**Comment by clinique** [comment]
In your configuration, can you replace `id` by `securityId` in the configuration of your thing ?

**Comment by clinique** [comment]
Can you also show the state of the item linked to 'live#local-picture-url' ? I think we're having the same issue than [this one](https://github.com/home-assistant/core/issues/67560#issuecomment-1291888550)

**Comment by MisterBop** [comment]
> Can you also show the state of the item linked to 'live#local-picture-url' ? I think we're having the same issue than [this one](https://github.com/home-assistant/core/issues/67560#issuecomment-1291888550)

Will have a look at a later stage. Need to focus on events and snapshot first

**Comment by MisterBop** [comment]
> In your configuration, can you replace `id` by `securityId` in the configuration of your thing ?

In configuration area or on channel level? Or both?

**Comment by clinique** [comment]
> > Can you also show the state of the item linked to 'live#local-picture-url' ? I think we're having the same issue than [this one](https://github.com/home-assistant/core/issues/67560#issuecomment-1291888550)
> 
> Will have a look at a later stage. Need to focus on events and snapshot first
I need this value to help debug events and snapshots (especially see what IP is provided by the API as local IP address).

**Comment by clinique** [comment]
```
UID: netatmo:home:xxxxxcccc:xxxxxxxxxxxxxxx
label: Home
thingTypeUID: netatmo:home
configuration:
 refreshInterval: 180
  id: xxxxxxxxxxxxxxxxxxxxx
```

Change to this:
```
UID: netatmo:home:xxxxxcccc:xxxxxxxxxxxxxxx
label: Home
thingTypeUID: netatmo:home
configuration:
  refreshInterval: 180
  securityId: xxxxxxxxxxxxxxxxxxxxx
```

**Comment by MisterBop** [comment]
Ok. Will do

**Comment by MisterBop** [comment]
> > Will have a look at a later stage. Need to focus on events and snapshot first
> > I need this value to help debug events and snapshots (especially see what IP is provided by the API as local IP address).
> 
> I need this to help investigate snapshots (especially see what Netatmo provides as local IP address for the CAM).

Need to pop off. Will follow up later in the day

**Comment by MisterBop** [comment]
First of all, please find my doorbell code

```
UID: netatmo:doorbell:xxxxxxxxxxx:xxxxxxxxxxxx
label: Netatmo-Doorbell
thingTypeUID: netatmo:doorbell
configuration:
  id: xxxxxxxxxxxxxxx
bridgeUID: netatmo:home:xxxxxxxx:xxxxxxxx
channels:
  - id: live#picture
    channelTypeUID: netatmo:live-picture
    label: Live Snapshot
    description: Camera Live Snapshot.
    configuration: {}
  - id: live#local-picture-url
    channelTypeUID: netatmo:live-picture-url
    label: Live Snapshot Local URL
    description: Local URL of the live snapshot for this camera.
    configuration: {}
  - id: status#sd-card
    channelTypeUID: netatmo:sd-card-status
    label: SD Card State
    description: State of the SD card
    configuration: {}
  - id: status#alim
    channelTypeUID: netatmo:alim-status
    label: Alim State
    description: State of the power connector
    configuration: {}
  - id: security-event#home-event
    channelTypeUID: netatmo:home-event
    label: Home Event
    description: null
    configuration: {}
  - id: sub-event#type
    channelTypeUID: netatmo:event-type
    label: Event Type
    description: Description of the event.
    configuration: {}
  - id: sub-event#time
    channelTypeUID: netatmo:timestamp
    label: Sub-Event Timestamp
    description: Moment when the sub-event occurred.
    configuration: {}
  - id: sub-event#message
    channelTypeUID: netatmo:message
    label: Message
    description: Message sent by Netatmo corresponding to given event.
    configuration: {}
  - id: sub-event#snapshot
    channelTypeUID: netatmo:event-picture
    label: Event Snapshot
    description: Capture image of the event.
    configuration: {}
  - id: sub-event#snapshot-url
    channelTypeUID: netatmo:event-picture-url
    label: Event Snapshot URL
    description: Url of the event snapshot.
    configuration: {}
  - id: sub-event#vignette
    channelTypeUID: netatmo:event-picture
    label: Vignette
    description: Vignette of the Snapshot.
    configuration: {}
  - id: sub-event#vignette-url
    channelTypeUID: netatmo:event-picture-url
    label: Vignette URL
    description: URL of the vignette.
    configuration: {}
  - id: last-event#type
    channelTypeUID: netatmo:event-type
    label: Event Type
    description: Description of the event.
    configuration: {}
  - id: last-event#video-status
    channelTypeUID: netatmo:video-status
    label: Video Status
    description: Status of the video (recording, deleted or available).
    configuration: {}
  - id: last-event#time
    channelTypeUID: netatmo:timestamp
    label: Event Timestamp
    description: Moment when event occurred.
    configuration: {}
  - id: last-event#local-video-url
    channelTypeUID: netatmo:video-url
    label: Video Local URL
    description: Local URL of the event recording.
    configuration: {}
  - id: last-event#vpn-video-url
    channelTypeUID: netatmo:video-url
    label: Video VPN URL
    description: URL of the event recording through Netatmo VPN.
    configuration: {}
  - id: signal#value
    channelTypeUID: netatmo:rssi
    label: Signal
    description: Signal strength indicator.
    configuration: {}
  - id: signal#strength
    channelTypeUID: system:signal-strength
    label: Signalstärke
    description: Zeigt die aktuelle Signalstärke an. Werte von 0 (Kein Signal) bis 4
      (Ausgezeichnet).
    configuration: {}
```

**Comment by MisterBop** [comment]
Assume I need to read the linked thread first… at the moment the value is „ NULL“

**Comment by MisterBop** [comment]
Via trace log I can see UrL like this. Just a sample bit of the full details 

https:\/\/netatmocameraimage.blob.core.windows.net\/production\/…

**Comment by MisterBop** [comment]
Did not yet manage to read the other thread. But I can see more details in the trace log than in one are populated in the webfrontend…like „human“ or „animal“.

**Comment by clinique** [comment]
> Referenc

No, you don't need to read it all. It was just for reference because I suspect we face the same problem.

**Comment by clinique** [comment]
> Via trace log I can see UrL like this. Just a sample bit of the full details
> 
> https://netatmocameraimage.blob.core.windows.net/production/…

Yes, this is likely to be your vpn-url channel. What I need is the local url channel value. You just need to link an item to the channel `live#local-picture-url` and see what value it gets.

**Comment by MisterBop** [comment]
That is what I did before. Remains „NULL“

**Comment by clinique** [comment]
> That is what I did before. Remains „NULL“

Can you see it in the logs changing ? It should not be NULL after first activation of the Thing

**Comment by clinique** [comment]
> > That is what I did before. Remains „NULL“
> 
> Can you see it in the logs changing ? It should not be NULL after first activation of the Thing
I saw on my configuration that the API answers me we a local adress formed like this `http://198.65...../dffdmksfdmk/`- but my local network is `192.168.0.xxx` and this generates NULL after that because 198.65 is not reachable. I want to see if you are in the same case.

**Comment by MisterBop** [comment]
Not this time and I can not really remember that I saw it in the past as I changed logging to trace. Let me do some tests later and extract the log to review via find command.

**Comment by MisterBop** [comment]
Nothing. No clear text IP in trace log. To ensure I did not missed out anything I have now linked all available channels with items. One doorbell and one presence outdoor cam

**Comment by MisterBop** [comment]
Sorry, just to ensure my bridge is well configured.

this is my config
```
UID: netatmo:account:xxxxxxxc
label: Netatmo Account
thingTypeUID: netatmo:account
configuration:
  reconnectInterval: 300
  clientSecret: xxxxxxxxx
  clientId: xxxxxxxcc
channels:
  - id: monitoring#request-count
    channelTypeUID: netatmo:request-count
    label: Request Count
    description: Number of requests transmitted to Netatmo API during the last hour.
    configuration: {}
```
 I can see a „monitoring „ channel in code page but not in the channel view?!

„Monitoring „ implies to me only values and no stream or snapshots.
