### ISSUE TITLE
floor map - Item rotation - retrieve angle from item state / value

### ISSUE THREAD

**Issue by ifs-net** [openhab/openhab-addons#16610]
In my case I am interested in showing sun direction in a floor map. Idea was to take an icon - for example f7:arrow_up - and set the sun direction via item rotation.

The problem ist, that the rotation can only be entered as a integer value from 0-360 and cannot be retrieved from an item state (e.g. =items.myitem.state as values can be used in other widgets).

Is it possible to enhance the "icon Rotation" in Marker configuration for use cases like this?

**Comment by stefan-hoehn** [comment]
First of I all I would recommend to ask these questions in the forum first because more people will likely notice it. ;-)

In your case, this is actually possible but it is not obvious. The reason it doesn't work straight away is that the UI element doesn't allow you to enter a text because it is a number spinner but there is a workaround:

- right click -> configure
- first enter a number (makes the second step easier) and save 
- right click -> yaml
- you'll see the configuration in the yaml notation and here you can add your expression:

````
component: oh-plan-marker
config:
  coords: 495.00568756273003,309.5406529279578
  icon: oh:battery
  name: Battery
  iconRotation: =items.testNumberState.state
slots:
  default: []
````

and here is proof that actually works ;-)

<img width="197" alt="image" src="https://github.com/openhab/openhab-addons/assets/5937600/5fb91809-98e2-47e7-918f-d90cc9d1f97c">

Hope that helps!
