### ISSUE TITLE
[network] (Docker) Still massively slowing down boon when extended default-adress-pools are used in /etc/docker/daemon.json

### ISSUE THREAD

**Issue by SHU-red** [openhab/openhab-addons#16810]
## Expected Behavior

When openHAB boots, the pingdevices shall be initialized relatively quickly.
The network-binding-things should be editable when clicking on them and not be loading forever.
The network-binding should not slow down other things to be discovered/initialized

## Current Behavior

Sorry for re-opening this, already referenced in:

- https://github.com/openhab/openhab-addons/issues/15437
- https://github.com/openhab/openhab-core/issues/3976
- https://community.openhab.org/t/openhab-4-0-1-and-network-pingdevice-on-docker-install-results-in-massive-threads/148658/3

As seen/documented in the linked discussions im pretty sure, that the combination
- using the network-binding
- configuring openHAB with `network_mode: host`
- using a extended docker-daemon default-address-pool
causes the network binding to scan/ping a extremely high range of IP addresses which results in CPU-load and/or delays in boot and usage.

I even upgraded my server recently to basically a gaming PC hardware and even then i am experiencing
- network-devices need a extremely long time to initialize (like 10 minutes) after boot
- these network-things are not accessible via MainUI --> Only loading skeleton can be seen
- this seems to slow down other things like mqtt binding/things too

I deinstalled the network binding and everything is fine

## Possible Solution

Not sure, because all of this was already discussed in the other topics but the result overall was something like "with the current version things should be better"

To repeat already discussed solutions:
- Possibility to limit/configure the relevant IP adress range in the network binding
- Using the "primary" address from mainUI settings

I have no advanced knowledge in all of these things but i feel like there could be something like a additional setting in the "advanced" section of the network-binding, extremely reducing the amount of scanned IPs to a normal range

My Hardware is way too overpowered for openHAB but this is significantly slowing down boot and interfering with the general openHAB stability

## Steps to Reproduce (for Bugs)

1. Use openHAB docker in network_mode: host
2. Install network binding
3. Extend default-address-pool
4. Boot

## Context

daemon.json
```
{
   "default-address-pools": [
        {
            "base":"172.17.0.0/12",
            "size":16
        },
        {
            "base":"192.168.0.0/16",
            "size":20
        }
    ]
}
```

## Your Environment

* Version used: openHAB 4.2.0.M3
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Firefox 126.0
* Operating System and version
```
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="40.20240416.3.1 (CoreOS)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora CoreOS 40.20240416.3.1"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='40.20240416.3.1'
```

**Comment by wborn** [comment]
Did you limit the network interfaces on your ping devices? This config option was added in https://github.com/openhab/openhab-addons/pull/16145.

**Comment by SHU-red** [comment]
Currently i deinstalled the Network binding and i am sending my magic packets via node-red

Can you just give me a very quick description/link on what to try?
I tired to follow your link and look at the PR but not sure how i should try it.

Is it
1. Re-install network binding
2. Limit IP-Ranges in network binding settings
3. Try

I would love to be able to set a network address range

**Comment by wborn** [comment]
You can limit the interfaces to use in the Advanced settings of your Thing:

![config](https://github.com/user-attachments/assets/caf5062e-59f9-4648-b864-353570832f43)

**Comment by SHU-red** [comment]
Understood
I will test it and give feedback
Thanks for caring

**Comment by lsiepel** [comment]
> Currently i deinstalled the Network binding and i am sending my magic packets via node-red
> 
> Can you just give me a very quick description/link on what to try? I tired to follow your link and look at the PR but not sure how i should try it.
> 
> Is it
> 
> 1. Re-install network binding
> 2. Limit IP-Ranges in network binding settings
> 3. Try
> 
> I would love to be able to set a network address range

1. Your subnets are huge. The /12 has 1 million addresses I can’t think of why you want it that large in a private setting. /24 or /22 is usually enough. 
The second one is also huge /16. I would expect more issues sooner or later that have nothing todo with openHAB. 
2. the added configuration option is documented. You can set/limit the interfaces in the thing configuration, it depends where if you use UI or file based config.

**Comment by SHU-red** [comment]
Thanks for your input
I will also check reducing my subsets

**Comment by SHU-red** [comment]
Setting interface for network devices seems to solve the "openhab things freezing" problem

I still see a high cpu load on openhab on my server
This may be due to the fact that @lsiepel  describes

Hoping this is not too off topic:

- In not an expert in network addresses
- Long time ago i think i also used this to get an idea of what is happening: https://straz.to/2021-09-08-docker-address-pools/
- This means, that the following config should be the docker-standard, which i only extended with the 10.99.0.0/16 addresses

```json
{
  "default-address-pools" : [
    {
      "base" : "172.17.0.0/12",
      "size" : 16
    },
    {
      "base" : "192.168.0.0/16",
      "size" : 20
    }
  ]
}
```

My problem was, that there are only 31 networks allowed in this config
I am running more than 31 thats why i need to extend this configuration

As a reminder, currently im running

```json
{
  "default-address-pools": [
        {
            "base":"172.17.0.0/12",
            "size":16
        },
	{
            "base":"192.168.0.0/16",
            "size":20
        },
	{
            "base":"10.99.0.0/16",
            "size":24
        }
    ]
}
```

Do you have any good suggestions using the default-config as basis and just extending it by something like the 10.99.0.0/16 address range?

Sorry for asking questions, i feel very unsettled regarding this topic

**Comment by SHU-red** [comment]
One more addition
I just tried to monitor my cpu load and during this i deinstalled the network binding again

![2024-07-13_13-27](https://github.com/user-attachments/assets/d2e81793-7902-4978-a6a8-826c7f0d258f)

As you see
- openhab (java) is utilizing my cpu permanent by 12%
- network binding present or not does not change anything

So im guessing im wrongly accusing the network binding for this utilization
I think this issue is closed and i have to check somehow if the CPU load is justifiable or if there is something else i have to dig in

Thank you

**Comment by SHU-red** [comment]
Sorry in advance for these many messages.
One last thing i did after deinstalling the network binding was to restart the openHAB docker container

And as you can see, the utilization of OH has drastically fallen
- left side: network biding was deinstalled but not rebooted
- middle: high load during restart of OH
- right side: utilization with no changes made, only restarted

So im back on the status of my reply above: https://github.com/openhab/openhab-addons/issues/16810#issuecomment-2226840631

![2024-07-13_13-34](https://github.com/user-attachments/assets/a6ad971a-1374-4e00-bd8a-c5f4f44b0369)

**Comment by wborn** [comment]
Maybe your tool can show the CPU usage per thread similar to  `top -H` ?
The threads have a name so those can help to identify what is consuming your CPU cycles.

**Comment by jsetton** [comment]
I have the same issue with the final release of OH 4.2 running in a Docker container using host network. There is still a huge delay at start-up for the configured `pingdevice` things to show up. Sometimes up to an hour to get the related things up. The same happens if I try to add a new `pingedevice` thing. First, the add new thing page takes a very long time to be displayed. Once added, it takes a while before it is shows up as well and when it's available, it takes a while to get the thing properties to show up.

I did everything listed above to limit the network discovery scope without any success. I decreased the Docker default address pools size to 24. I also selected the network interfaces to use for each of my configured `pingdevice` things. The only difference is that the CPU is pretty much idling when the delay is happening. Looking at trace logs for the binding, not much is happening during that time as well. Each delay seems to be related to some kind of timeout that isn't logged.

I also ran a minimal test using a new Docker container using host network and only installed the `network` binding. I experienced no issue in OH 4.1 while I did with OH 4.2. When I ran the container on its own network, the issue no longer happens with OH 4.2. Something has changed between the two releases. For reference, I have 33 network interfaces on my Docker host.

**Comment by SHU-red** [comment]
Sorry for taking my time. Very busy and wanted to observe this for a few days.

I have no idea why this probem is so hard do chase but since setting the Interfaces to only my network interface it seems that the load is ok, ping devices are working and opening the thing-settings is .... at least ok

I want to highlight again at this point that i have a very powerful homeserver --> Evern running this machine i can still feel a lag in opening the pingdevices

So i can understand the example of @jsetton especially if you are running a lower-powered machine

Running:

```
runtimeInfo:
  version: 4.2.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.11
  javaVendor: Debian
  osName: Linux
  osVersion: 6.8.5-301.fc40.x86_64
  osArchitecture: amd64
  availableProcessors: 16
  freeMemory: 639302192
  totalMemory: 1593835520
  uptime: 196953
  startLevel: 100
addons:
  - binding-astro
  - binding-chromecast
  - binding-fronius
  - binding-http
  - binding-ipcamera
  - binding-lgwebos
  - binding-luxtronikheatpump
  - binding-mqtt
  - binding-network
  - binding-ntp
  - binding-openweathermap
  - binding-shelly
  - binding-somfytahoma
  - binding-telegram
  - binding-wifiled
  - binding-wled
  - misc-metrics
  - misc-openhabcloud
  - persistence-influxdb
  - transformation-jsonpath
  - ui-habot
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0
timestamp: 2024-07-17T19:36:13.502Z
```

**Comment by jsetton** [comment]
> So i can understand the example of @jsetton especially if you are running a lower-powered machine

I don't think this is related to a resource issue since there is a clear difference in behavior on the same hardware between OH versions. Something changed between OH 4.1.0 and 4.1.1. Also, it may not be solely related to running OH in a Docker container as per the forum post linked above.

The `network` binding had a patch applied in 4.1.1 related to network interfaces filtering parameter but looking at the code, I can't see what could cause that this delay issue. The only reason I can see is some library update from upstream. Hopefully @wborn would have a better insight on this.

**Comment by lsiepel** [comment]
Would you be able to get a debug log for the full 10-15 mins of the slow start for the binding?

**Comment by lsiepel** [comment]
@yndtrud @jsetton 
Could you try this jar https://1drv.ms/u/s!AnMcxmvEeupwj49DlPN-znfkoxHM6w?e=wGfqko it should work on 4.3.0. During discovery, the networkInterfaceNames is empty and all names are determined form your system without checking ifUp. So added that check.

1. Make sure you have openHAB 4.3.0
2. uninstall network binding (does not affect your configuration of items/channels etc)
3. drop the jar file in your addon folder
4. report back your results regarding discovery. if there are still issues, please add a trace log.

**Comment by jsetton** [comment]
@lsiepel I ran the above version and I am experiencing the same slowness issue as before. Because my OH docker container has access to the host interfaces, the `network` binding has access to ~70 interfaces up in my environment.

Per the attached trace logs, it takes about 30 minutes for the binding to initialize the first `pingdevice` thing. Then another ~25 minutes between each thing after that. All my `pingdevice` things are setup with `retry=2, useIOSWakeUp=false, networkInterfaceNames="<interface>"`.

**Timings**
```
01:57:18 binding start
02:29:19 host1 pingdevice start
02:55:04 host2 pingdevice start
03:20:50 host3 pingdevice start
03:46:36 host4 pingdevice start
04:12:20 host5 pingdevice start
04:38:06 host6 pingdevice start
05:03:51 host7 pingdevice start
05:29:37 host8 pingdevice start
05:55:22 host9 pingdevice start
06:21:08 host10 pingdevice start
06:46:54 host11 pingdevice start
```

**Logs**

[network.zip](https://github.com/user-attachments/files/18246811/network.zip)

**Comment by lsiepel** [comment]
> @lsiepel I ran the above version and I am experiencing the same slowness issue as before. Because my OH docker container has access to the host interfaces, the `network` binding has access to ~70 interfaces up in my environment.
> 
> Per the attached trace logs, it takes about 30 minutes for the binding to initialize the first `pingdevice` thing. Then another ~25 minutes between each thing after that. All my `pingdevice` things are setup with `retry=2, useIOSWakeUp=false, networkInterfaceNames="<interface>"`.
> 
> **Timings**
> 
> ```
> 01:57:18 binding start
> 02:29:19 host1 pingdevice start
> 02:55:04 host2 pingdevice start
> 03:20:50 host3 pingdevice start
> 03:46:36 host4 pingdevice start
> 04:12:20 host5 pingdevice start
> 04:38:06 host6 pingdevice start
> 05:03:51 host7 pingdevice start
> 05:29:37 host8 pingdevice start
> 05:55:22 host9 pingdevice start
> 06:21:08 host10 pingdevice start
> 06:46:54 host11 pingdevice start
> ```
> 
> **Logs**
> 
> [network.zip](https://github.com/user-attachments/files/18246811/network.zip)

`networkInterfaceNames` is set per Thing. The issue occurs when discovery is run when the Thing has yet to be discovered.
The only solution i see is to introduce a binding level configuration option that mimics the `networkInterfaceNames`. This would make it available for the discovery proces.
Do you see some kind of logic (or assumption) that would make it possible to limit the interfaces when the setting has not yet been set by the user (default)?
Maybe we could limit it to the primairy interface by default?

**Comment by jsetton** [comment]
> Do you see some kind of logic (or assumption) that would make it possible to limit the interfaces when the setting has not yet been set by the user (default)?

Not sure but something has changed between OH 4.1.0 and 4.1.1 based on my testing. Unfortunately, there isn't much logged by the binding that would explain what it is waiting on.

> Maybe we could limit it to the primairy interface by default?

Agreed.

**Comment by lsiepel** [comment]
Updated the jar with additional logging. 

Obviously if such a range is provided, it can take long times to  complete. Currently the amount of parralel threads is `cpu cores * 2` This could be lowered (or made configurable), probably resulting in a more responsive system, but the amount of time to complete the scan is increasing.

**Comment by yndtrud** [comment]
> Updated the jar with additional logging.
> 
> Obviously if such a range is provided, it can take long times to complete. Currently the amount of parralel threads is `cpu cores * 2` This could be lowered (or made configurable), probably resulting in a more responsive system, but the amount of time to complete the scan is increasing.
> 
> Maybe said before, but make sure background scan is disabled. I would nog expect slow binding start as no scan is performed in that case.

Hi. I tested the binding, I'm sending you the logs.

Workstation:
```
Microsoft Windows 10 Pro With Hyper-V role
Intel Core i7-10700K 4700Mhz/DDR4-3600-32GB/SSD512GB/RTX4060Ti
Hyper-V Virtual Ethernet Adapter #2  (192.168.13.1)/Physical: Intel I225-V Ethernet Controller
```

OpenHAB:
```
runtimeInfo:
  version: 5.0.0.M2
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: M:\servers\devenv\openhab\oh-system-active\conf
  userdataFolder: M:\servers\devenv\openhab\oh-system-active\userdata
  logFolder: M:\servers\devenv\openhab\oh-system-active\userdata\logs
  javaVersion: 21.0.7
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu21.42+19-CA
  osName: Windows 10
  osVersion: "10.0"
  osArchitecture: amd64
  availableProcessors: 16
  freeMemory: 30964080
  totalMemory: 125829120
  uptime: 151
  startLevel: 70
addons:
  - persistence-rrd4j
  - transformation-map
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 16
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/137.0.0.0 Safari/537.36
timestamp: 2025-06-04T08:46:45.601Z
```

Addon
```
jar: org.openhab.binding.network-5.0.0-SNAPSHOT.jar
SHA256: 914d3e3f38f055f8784f8029eb8c3f72f23c165a77136c235a13ac95e7dad1e4 
```

How it works:
1. Items created in the interface appear all at once (when entering the page with items after launch) in the ERROR:HANDLER state, then they go to the NOT_YET_READY state (this is fast, apparently when the binding is loaded). Each item (device/service) is initialized for at least 20 seconds, always in turn. First item -> 20 seconds initialization->> ONLINE -> next item... and so on until all items are initialized.
3. Then each item is loaded from the file (filename.things). They appear in the list of items in turn: first with the UNINITIALIZED status, then ONLINE. Each item (device/service) is initialized for at least 20 seconds. An item appears in the list -> UNINITIALIZED > 20 seconds initialization -> ONLINE-> the next item appears... and so on until all items appear. It seems to me that all items with the UNINITIALIZED state should appear at once, then you need to start initializing them.
4. When trying to open a thing (it doesn't matter: from a file or created in the interface, UNINITIALIZED  or ONLINE) you need to wait at least 10 seconds. Saving changes also requires waiting.

And another very important thing: because the initialization of network binding things is very slow, the whole openhub in parallel takes a very, very, very long time to initialize all other things of other addons. As soon as you delete the network binding, everything is immediately initialized instantly. Until the network binding finishes initializing its things, all other addons will slow down.

On my production server, now everything works more or less well, but on test machines everything slows down very much. I transferred the full configuration from a weak production server to a powerful test machine and the network binding started to slow down.

In the attached file Networks_jdk21.txt you can see the list of my networks on this computer. It is possible that the system slows down when opening a thing because of this. I think that it would be correct (in this situation) to configure the list of networks in the network binding settings and show them when configuring things and use them when working with things. By the way, in Java v21 they remembered the name of the networks (under Windows for sure, I have not checked under Linux), for example from eth5 to ethernet_32777. So in any case, users will have to change the configuration in OH5 when updating.

In search of a solution to the problem, I downloaded the source code of version 4.1.x, 4.3.x and 5.0.0M2 I compared them and found out that the main change in them is the way of detecting the presence of devices in thread. I tried debugging in version 4.3 (configured Visual Studio Code), but could not find the reason for such delays during initialization. If I can look somewhere in the code, you tell me - I will check. I am not strong in Java and therefore the code is difficult for me in some places.

[oh-v5.0.0-M2.zip](https://github.com/user-attachments/files/20589126/oh-v5.0.0-M2.zip)
