### ISSUE TITLE
Querying persistence services with date filter gives unexpected results

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#17028]
I experience some inconsistent results when trying to create the same chart using different persistence services.

I think that the issue might be that [FilterCriteria](https://www.openhab.org/javadoc/latest/org/openhab/core/persistence/filtercriteria) is only sparsely documented, so implementations could have different interpretations.

Specifically, how should `beginDate` and `endDate` be applied?
- Should only state changes within the boundaries of [`beginDate` : `endDate`[ be returned?
- Or should all states valid within the boundaries of [`beginDate` : `endDate`[ be returned, including the state still valid when entering the time interval?
- Please note the `[` above. Normally end date in date intervals are considered **inclusive**, while end datetime in datetime intervals are considered **exclusive**. I assume the same logic should be applied here? Changing this would require changes in both Javadoc and implementations though. See openhab/openhab-core#3164. This is a minor side-comment, not the main issue.

The problem with the first interpretation is: How would it then be possible to query the state valid at any given moment? To be sure, you would have to provide a very old beginDate, and as a result you would get way too much data returned.

The JDBC persistence services applies this interpretation:

https://github.com/openhab/openhab-addons/blob/4f322cc663ef51b6b4afccedfc48518d045de847/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java#L541-L554

And as a result when trying to create a chart:

```
2024-07-09 16:18:17.642 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::query queryString = SELECT time, value FROM EnergiDataService_GridTariff WHERE TIME>='2024-07-09 16:17:40' AND TIME<='2024-07-10 16:17:40' ORDER BY time ASC
2024-07-09 16:18:17.643 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::doGetHistItemFilterQuery sql=SELECT time, value FROM EnergiDataService_GridTariff WHERE TIME>='2024-07-09 16:17:40' AND TIME<='2024-07-10 16:17:40' ORDER BY time ASC
```

the first value here is missed:

| time                    | value      |
| ----------------------- | ---------: |
| **2024-07-09 06:00:00.000** | 0.20646875 |
| 2024-07-09 17:00:00.000 | 0.5368175  |
| 2024-07-09 21:00:00.000 | 0.20646875 |
| 2024-07-10 00:00:00.000 | 0.137645   |
| 2024-07-10 06:00:00.000 | 0.20646875 |

## Expected Behavior

I would expect the first row above to be included in the result set as well, since that value is valid until the new value at 2024-07-09 17:00:00.000 replaces it.

## Current Behavior

Only state changes that took place within the queried period are returned, not the last value before the period.

## Possible Solution

The query could be adapted to take this into consideration, but the Javadoc should be updated as well, and all other implementations should be checked.

## Steps to Reproduce

Create a chart like in the example below.

## Context

I'm trying to create a stacked bar chart representing electricity prices with different components on top of each other. With rrd4j it looks like this:

![image](https://github.com/openhab/openhab-addons/assets/19519842/5b108549-b1ca-4985-afee-fc3f53937e3d)

Given this code:
```yaml
config:
  future: true
  label: Elpriser
  period: D
  sidebar: true
slots:
  grid:
    - component: oh-chart-grid
      config: {}
  series:
    - component: oh-time-series
      config:
        gridIndex: 0
        item: EnergiDataService_SpotPrice
        name: Spotpris
        type: bar
        xAxisIndex: 0
        yAxisIndex: 0
        stack: one
        service: rrd4j
    - component: oh-time-series
      config:
        gridIndex: 0
        item: EnergiDataService_GridTariff
        name: Nettarif
        type: bar
        xAxisIndex: 0
        yAxisIndex: 0
        stack: one
        service: rrd4j
  xAxis:
    - component: oh-time-axis
      config:
        gridIndex: 0
  yAxis:
    - component: oh-value-axis
      config:
        gridIndex: 0
```

With JDBC (MySQL) it looks like this:

![image](https://github.com/openhab/openhab-addons/assets/19519842/ce9f648b-c5eb-4e60-a5f6-3494d4af9ec1)

The issue is very likely related to the way the persistence service is queried, since there are no redundant updates, but only actual state changes (item `EnergiDataService_GridTariff`):

| time                    | value      |
| ----------------------- | ---------: |
| 2024-07-08 13:00:00.000 | 0.20646875 |
| 2024-07-08 17:00:00.000 | 0.5368175  |
| 2024-07-08 21:00:00.000 | 0.20646875 |
| 2024-07-09 00:00:00.000 | 0.137645   |
| 2024-07-09 06:00:00.000 | 0.20646875 |
| 2024-07-09 17:00:00.000 | 0.5368175  |
| 2024-07-09 21:00:00.000 | 0.20646875 |
| 2024-07-10 00:00:00.000 | 0.137645   |
| 2024-07-10 06:00:00.000 | 0.20646875 |

Please note that this is not the only issue, since even values within the period are not repeated. So either I have the wrong understanding of the chart functionality (quite likely) or my example would still not work even if FilterDate beginDate is clarified and fixed.

## Your Environment
* Version used: 4.2
