### ISSUE TITLE
Adding go-e charger ends with error java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by Boldfor** [openhab/openhab-addons#17114]
Adding a go-e charger (Gemini flex 22 kW, produced 2024 / 01) as a thing ends with a java error.

## Expected Behavior
When adding a charger by adding a thing, specifying the IP address, the thing goes online without an error.

## Current Behavior
When installing the binding, adding a charger by adding a thing, specifying the IP address (as shown in the go-e App), the thing does not come online:

`2024-07-19 21:48:04.520 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'goecharger:goe:go-eCharger' changed from OFFLINE (COMMUNICATION_ERROR): java.net.NoRouteToHostException: No route to host to OFFLINE (COMMUNICATION_ERROR): java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $`

## Possible Solution
Not sure if this has something to do with the problem, but when installing the add-on, the "installing-icon" (in constrast to installing other add-ons) keeps circling forever. When re-loading the binding, it is listed as installed.
![IMG_1204](https://github.com/user-attachments/assets/ff270cd5-f9cd-4580-9b80-6a39333c8741)

## Steps to Reproduce (for Bugs)

1. Install binding
2. Add go-e thing
3. Specify IP address as shown in app
4. Use "1", "2" or <blank> as the API-version in the thing-configuration all throw the same error

## Context
All other bindings in my openHAB installation work without any problems. WiFi-Repeater is ~1 m away from the charger (WiFi field strength is 100%).

## Your Environment
```
runtimeInfo:
  version: 4.2.0
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.11
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.0-rpi8-rpi-2712
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 384336872
  totalMemory: 681574400
  uptime: 233795
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-amazonechocontrol
  - binding-gardena
  - binding-goecharger
  - binding-homematic
  - binding-irobot
  - binding-mqtt
  - binding-systeminfo
  - binding-yamahamusiccast
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-regex
  - transformation-xpath
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
timestamp: 2024-07-21T11:15:32.254Z
```
