### ISSUE TITLE
[http] POST request - Option for empty "content"

### ISSUE THREAD

**Issue by elcodeo** [openhab/openhab-addons#17241]
## Intro
As already mentioned in the community post [HTTP Binding: POST “content” not empty](https://community.openhab.org/t/http-binding-post-content-not-empty/131966) it is not possible to send a POST request with an empty "content". Therefore I suggest to include an option (for example: "Leave content empty") for POST requests.

## Background
I’m trying to deal with the REST API of “Proxmox” to start/stop virtual machines through openHAB. The API accepts the command by url only and rejects requests with the command as "content". Sending commands as a GET request will be rejected, too.

## Current environment
openHAB 4.3.0, Build 4215

#### Thing & Channel:
```
UID: http:url:proxmoxPVE
label: Proxmox Server
thingTypeUID: http:url
configuration:
  authMode: TOKEN
  headers:
    - Authorization=PVEAPIToken=XXXXX
  ignoreSSLErrors: true
  baseURL: https://XYZ:8006/api2/json
  delay: 0
  stateMethod: GET
  refresh: 30
  commandMethod: POST
  contentType: application/json
  timeout: 3000
  bufferSize: 2048
channels:
  - id: lxc117
    channelTypeUID: http:switch
    label: LXC Test1
    description: ""
    configuration:
      mode: READWRITE
      onValue: running
      commandTransformation: MAP:proxmox.map
      offValue: stopped
      stateExtension: /nodes/pve/lxc/117/status/current
      commandExtension: /nodes/pve/lxc/117/status/%2$s
      stateTransformation: JSONPATH:$.data.status
```

#### proxmox.map
```
running=start
stopped=shutdown
```
