### ISSUE TITLE
[aWATTar] Bestprice items are set to UNDEF at 0 a.m.

### ISSUE THREAD

**Issue by aMU5Ed** [openhab/openhab-addons#17316]
## Expected Behavior
Best Price items should be recalculated when the new prices are fetched from the aWATTar API

## Current Behavior
With the upgrade from 4.2.0 to 4.2.1 the addon fetches the prices and delivers the value to the configured items for the best-price calculation.
This works from 2 p.m. until 0 a.m. With 0 a.m. the timeslots and the switches are set to UNDEF and therefore do not work until 2 p.m.

## Possible Solution
Best Price items should be recalculated when the new prices are fetched from the aWATTar API

## Steps to Reproduce (for Bugs)
1. Items are properly filled at 2 p.m.
2. Wait for 0 a.m. ;-)

## Context
Bestprice calculation

## Your Environment
Raspberry Pi 4 8GB
Ubuntu 24.04 LTS
zulu Java 17.46.19 aarch64
OpenHab 4.2.1 Release build

**Comment by cybermcm** [comment]
I can confirm this, would really appreciate the desired behavior described in OP

**Comment by aMU5Ed** [comment]
@J-N-K  could you please assign the bug to the maintainer of this add-on?

**Comment by Wolfgang1966** [comment]
Last changes were done by @tl-photography, as far as I am aware of.

**Comment by tl-photography** [comment]
Hi,

the refresh handling of 4.2.1 is still the "old" way: https://github.com/openhab/openhab-addons/blob/4.2.1/bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java#L182

My fix with more refreshes during the day will be probably included in the next release: https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java#L186

The current handling should once the bride signals a refresh, do so, but only at 1500 or when the bridge is reloaded.

**Comment by tl-photography** [comment]
@aMU5Ed  can you share your bridge config?

**Comment by cybermcm** [comment]
@tl-photography: I've the same problem, values get deleted at 0 a.m.
my config:
```
UID: awattar:bridge:aabbccddee
label: aWATTar Bridge
thingTypeUID: awattar:bridge
configuration:
  country: AT
  vatPercent: 20
  basePrice: 0
```

**Comment by Herschdorfer** [comment]
@cybermcm thanks this looks fine. Doe you have also the thing config handy?

**Comment by cybermcm** [comment]
@Herschdorfer: Do you mean the best price thing?
```
UID: awattar:bestprice:aabbccddee:6368db731f
label: aWATTar best price
thingTypeUID: awattar:bestprice
configuration:
  length: 3
  rangeDuration: 24
  rangeStart: 0
  consecutive: true
bridgeUID: awattar:bridge:aabbccddee
channels:
  - id: active
    channelTypeUID: awattar:switch-type
    label: Active
    description: Currently activated
    configuration: {}
  - id: start
    channelTypeUID: awattar:start-time-stamp
    label: Starttime
    description: Starting time of period.
    configuration: {}
  - id: end
    channelTypeUID: awattar:end-time-stamp
    label: end-time-stamp
    description: End time of period.
    configuration: {}
  - id: countdown
    channelTypeUID: awattar:countdown-type
    label: Countdown
    description: Time until start of period.
    configuration: {}
  - id: remaining
    channelTypeUID: awattar:remaining-type
    label: Remaining
    description: Time until end of period.
    configuration: {}
  - id: hours
    channelTypeUID: awattar:hours-type
    label: Hours
    description: A list of all hours within this bestprice range
    configuration: {}

```
