### ISSUE TITLE
[surepetcare] HANDLER_INITIALIZING_ERROR on API thing after connecting flap

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-addons#17497]
## Current Behavior

After connecting a surepetcare connected flap to my account/hub, the API thing has an error:

> Status: UNINITIALIZED
> HANDLER_INITIALIZING_ERROR
> Cannot invoke "org.openhab.binding.surepetcare.internal.dto.SurePetcareDeviceCurfewList.get(int)" because "device.control.curfewList" is null 

## Your Environment

````
runtimeInfo:
  version: 4.2.1
  buildString: Release Build
locale: de-DE
````
