### ISSUE TITLE
[miio] Add support for Xiaomi Smart Air Purifier 4 Lite (zhimi.airp.rmb1)

### ISSUE THREAD

**Issue by moodyblue** [openhab/openhab-addons#17572]
## Your Environment
* Version used: openHAB 4.3.0.M2

## Initial steps
I made a scan and the binding created a thing
```
UID: miio:generic:2A096791
label: Purificador de Ar
thingTypeUID: miio:unsupported
configuration:
  cloudServer: de
  refreshInterval: 30
  host: 192.168.129.170
  model: zhimi.airp.rmb1
  communication: direct
  deviceId: "705259409"
  timeout: 15000
  token: 90073a53f5f1feb9ceccfff9d86790a5
channels:
  - id: network#ssid
    channelTypeUID: miio:ssid
    label: SSID
    configuration: {}
  - id: network#bssid
    channelTypeUID: miio:bssid
    label: BSSID
    configuration: {}
  - id: network#rssi
    channelTypeUID: miio:rssi
    label: RSSI
    configuration: {}
  - id: network#life
    channelTypeUID: miio:life
    label: Life
    configuration: {}
  - id: actions#power
    channelTypeUID: miio:power
    label: Power On/Off
    configuration: {}
  - id: actions#commands
    channelTypeUID: miio:commands
    label: Execute Command
    configuration: {}
  - id: actions#rpc
    channelTypeUID: miio:rpc
    label: Execute RPC (cloud) Command
    configuration: {}
  - id: actions#testmiot
    channelTypeUID: miio:testmiot
    label: (experimental) Create channels for new/unsupported devices (MIOT protocol)
    description: Create experimental support for MIOT protocol devices based on the
      online specification. Check your log, share your results.
    configuration: {}
  - id: actions#testcommands
    channelTypeUID: miio:testcommands
    label: (experimental) Create channels / test properties for unsupported devices
      (legacy protocol)
    description: Execute test for all known properties to find channels supported by
      your device. This is for older / legacy devices, newer devices mostly use
      MIOT. Check your log, share your results.
    configuration: {}
```
The thing is offline, here is the log
```
2024-10-15 10:38:18.601 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'miio:generic:2A096791' changed from OFFLINE (COMMUNICATION_ERROR) to OFFLINE
2024-10-15 10:38:18.602 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'miio:generic:2A096791' changed from OFFLINE to OFFLINE (COMMUNICATION_ERROR)
```
