### ISSUE TITLE
[govee] LAN API (Single Light Control)

### ISSUE THREAD

**Issue by Oekel** [openhab/openhab-addons#17713]
I am Using the Current stable Version 4.2.0
(Including the Govee LAN Binding)

Sucessfully using this Binding with a H7066 (It is RGBIC 4x Spot)

https://developer.govee.com/reference/control-you-devices#segment_color_setting
Is telling about individual control of the lights (divice might support, course I can indivdual control them with Bluetooth-App)

But insight OpenHAB there the Thing only comes with 3 Channels (controlling all 4 together)
```
channels:
  - id: color
    channelTypeUID: system:color
  - id: color-temperature
    channelTypeUID: system:color-temperature
  - id: color-temperature-abs
```

Would be great if the Binding can support this.

**Hint:
Its not totally optional** (could be referenced as bug)
Becourse when you overwrite the individual brightness with the App of one Spot than the Max-Value over API is also limited.
So you have to get sure that Mobile-App is set to 100% Brightness first to get all output via API.
