### ISSUE TITLE
evcc binding - gridPower is now grid.power

### ISSUE THREAD

**Issue by willyfromtheblock** [openhab/openhab-addons#18148]
evcc updated their API with version 0.133.0 [Latest](https://github.com/evcc-io/evcc/releases/latest)

```
channels:
  - id: general#gridPower
    channelTypeUID: evcc:gridPower
    configuration: {}

```
is no longer correct, since it is trying to read **gridPower**, it should be **grid.power** now

![Image](https://github.com/user-attachments/assets/468e23d9-fbb3-4960-bf2f-be0f8de07876)
