### ISSUE TITLE
[AndroidTV] PhilipsTV power channel change values after thing  thing got offline

### ISSUE THREAD

**Issue by NikolayKash** [openhab/openhab-addons#18159]
## Expected Behavior
Keep value as OFF, instead setting it ON and immediately set it to OFF after thing got online  

## Current Behavior
Item value is OFF
Thing got OFFINE
Thing get ONLINE
Item value set to ON
Almost the same time it gets OFF.

PSA screenshot

#

![Image](https://github.com/user-attachments/assets/82f50449-8d62-4f76-a0c0-f046ddf21bd6)

## Possible Solution
keep OFF value instead of ON

## Steps to Reproduce (for Bugs)
Item value is OFF
Thing got OFFINE
Thing get ONLINE
Item value set to ON
Almost the same time it gets OFF. 

## Context
I have a PhilipsTV and use  this configuration

![Image](https://github.com/user-attachments/assets/17dea3b0-972d-4e20-a96f-edeeac271346)

As I persist state of TV there are lots of ON OFF entries generated during a day while TV was off full day.

Could it be related to this logic?

https://github.com/openhab/openhab-addons/blob/4dfaef97c3d8e0a663caf5c81aa0c797b0f58bcc/bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/philipstv/service/PowerService.java#L69

Debug log around the issue:

![Image](https://github.com/user-attachments/assets/7eec8f07-f70b-4b4d-addc-90b793172101)

## Your Environment
```
runtimeInfo:
  version: 4.3.2
  buildString: Release Build
systemInfo:
  javaVersion: 17.0.13
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 6.8.0-51-generic

addons:
  - binding-androidtv
  
clientInfo:
  device:
    desktop: true
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: Linux x86_64

```
