### ISSUE TITLE
XMPPClient Binding has no channels

### ISSUE THREAD

**Issue by NCC1701M** [openhab/openhab-addons#18196]
## Expected Behavior
Regarding to the [Documentation](https://www.openhab.org/addons/bindings/xmppclient/#example-rules), I should listen to a channel named `xmpp_command` when I want a rule to run when the binding receives a message. 

## Current Behavior
I can't select any channel because a XMPPClient thing doesn't have any channels:

![Image](https://github.com/user-attachments/assets/54182f80-c617-44c9-b52b-1ad4887cf3c4)

![Image](https://github.com/user-attachments/assets/aa964a43-6664-4ef3-94eb-c42d32d36c09)

![Image](https://github.com/user-attachments/assets/eb6b4c23-1dad-471f-8dab-56ae937206bb)

![Image](https://github.com/user-attachments/assets/4c65e185-8b8a-424b-befd-6646f98cf262)

## Steps to Reproduce (for Bugs)

1. Install the binding
2. Create and configure a thing for this binding 

## Context
I want to receive messages by the xmpp binding.

## Your Environment
- Version used:
  - openHAB: 4.3.2
  - XMPPClient Binding: 4.3.2
- Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Firefox 134.0.1
- Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Running in a Container using the latest 4.3.2 image

**Comment by lsiepel** [comment]
Did you try to add the channel manually?
Maybe @riorado or @skazi0 can be of any help.

**Comment by riorado** [comment]
Yes, tried without success. Always the same error.

**Comment by skazi0** [comment]
I use files for configuration but I also tried the UI setup and got this:

![Image](https://github.com/user-attachments/assets/ccbf6d7c-387c-487d-81af-28d04cc108e8)

![Image](https://github.com/user-attachments/assets/de65a7d7-c0df-419f-9f12-57af62a9dda5)

The "Code" view of this:
```
UID: xmppclient:xmppBridge:e5495c5687
label: XMPP Client
thingTypeUID: xmppclient:xmppBridge
configuration:
  host: <redacted>
  password: <redacted>
  securityMode: required
  domain: <redacted>
  username: openhab
channels:
  - id: xmpp_command
    channelTypeUID: xmppclient:publishTrigger
    label: Publish Trigger
    description: ""
    configuration:
      separator: "##"
```
