### ISSUE TITLE
[miio] Add support for Xiaomi Smart Air Fryer 6.5L (careli.fryer.maf10a)

### ISSUE THREAD

**Issue by moodyblue** [openhab/openhab-addons#18258]
## Your Environment
* Version used: 4.3.2

## Initial Steps
I made a scan and the binding created a thing
```
UID: miio:generic:2CD741FF
label: Air Fryer 6.5L
thingTypeUID: miio:unsupported
configuration:
  cloudServer: de
  refreshInterval: 30
  host: 192.168.132.101
  model: careli.fryer.maf10a
  communication: cloud
  deviceId: "752304639"
  timeout: 15000
  token: ead43140249b7f739295aadd215f1287
channels:
  - id: network#ssid
    channelTypeUID: miio:ssid
    label: SSID
    configuration: {}
  - id: network#bssid
    channelTypeUID: miio:bssid
    label: BSSID
    configuration: {}
  - id: network#rssi
    channelTypeUID: miio:rssi
    label: RSSI
    configuration: {}
  - id: network#life
    channelTypeUID: miio:life
    label: Life
    configuration: {}
  - id: actions#power
    channelTypeUID: miio:power
    label: Power On/Off
    configuration: {}
  - id: actions#commands
    channelTypeUID: miio:commands
    label: Execute Command
    configuration: {}
  - id: actions#rpc
    channelTypeUID: miio:rpc
    label: Execute RPC (cloud) Command
    configuration: {}
  - id: actions#testmiot
    channelTypeUID: miio:testmiot
    label: (experimental) Create channels for new/unsupported devices (MIOT protocol)
    description: Create experimental support for MIOT protocol devices based on the
      online specification. Check your log, share your results.
    configuration: {}
  - id: actions#testcommands
    channelTypeUID: miio:testcommands
    label: (experimental) Create channels / test properties for unsupported devices
      (legacy protocol)
    description: Execute test for all known properties to find channels supported by
      your device. This is for older / legacy devices, newer devices mostly use
      MIOT. Check your log, share your results.
    configuration: {}
```
This device is not in the supported devices list, here is the log with some relevant info:
```
Database file created:/etc/openhab/misc/miio/careli.fryer.maf10a-miot-experimental.json
{
	"deviceMapping": {
		"id": [
			"careli.fryer.maf10a"
		],
		"propertyMethod": "get_properties",
		"maxProperties": 1,
		"channels": [
			{
				"property": "",
				"friendlyName": "Actions",
				"channel": "actions",
				"type": "String",
				"stateDescription": {
					"options": [
						{
							"value": "air-fryer-start-cook",
							"label": "Air Fryer Start Cook"
						},
						{
							"value": "air-fryer-cancel-cooking",
							"label": "Air Fryer Cancel Cooking"
						},
						{
							"value": "air-fryer-pause",
							"label": "Air Fryer Pause"
						},
						{
							"value": "air-fryer-resume-cook",
							"label": "Air Fryer Resume Cook"
						},
						{
							"value": "air-fryer-start-recipe-cook",
							"label": "Air Fryer Start Recipe Cook"
						}
					]
				},
				"refresh": false,
				"actions": [
					{
						"command": "action",
						"parameterType": "EMPTY",
						"siid": 2,
						"aiid": 1,
						"condition": {
							"name": "matchValue",
							"parameters": [
								{
									"matchValue": "air-fryer-start-cook"
								}
							]
						}
					},
					{
						"command": "action",
						"parameterType": "EMPTY",
						"siid": 2,
						"aiid": 2,
						"condition": {
							"name": "matchValue",
							"parameters": [
								{
									"matchValue": "air-fryer-cancel-cooking"
								}
							]
						}
					},
					{
						"command": "action",
						"parameterType": "EMPTY",
						"siid": 2,
						"aiid": 3,
						"condition": {
							"name": "matchValue",
							"parameters": [
								{
									"matchValue": "air-fryer-pause"
								}
							]
						}
					},
					{
						"command": "action",
						"parameterType": "EMPTY",
						"siid": 2,
						"aiid": 4,
						"condition": {
							"name": "matchValue",
							"parameters": [
								{
									"matchValue": "air-fryer-resume-cook"
								}
							]
						}
					},
					{
						"command": "action",
						"parameterType": "UNKNOWN",
						"parameters": [
							3,
							4,
							7,
							10,
							11,
							13,
							16,
							17,
							18.0
						],
						"siid": 2,
						"aiid": 5,
						"condition": {
							"name": "matchValue",
							"parameters": [
								{
									"matchValue": "air-fryer-start-recipe-cook"
								}
							]
						}
					}
				]
			},
			{
				"property": "status",
				"siid": 2,
				"piid": 1,
				"friendlyName": "Air Fryer - Status",
				"channel": "status",
				"type": "Number",
				"stateDescription": {
					"readOnly": true,
					"options": [
						{
							"value": "0",
							"label": "Off"
						},
						{
							"value": "1",
							"label": "Idle"
						},
						{
							"value": "2",
							"label": "Paused"
						},
						{
							"value": "3",
							"label": "Delay"
						},
						{
							"value": "4",
							"label": "Cooking"
						},
						{
							"value": "5",
							"label": "Preheat "
						},
						{
							"value": "6",
							"label": "Cooking Completed"
						},
						{
							"value": "7",
							"label": "Preheat Completed"
						},
						{
							"value": "8",
							"label": "Preheat Paused"
						},
						{
							"value": "9",
							"label": "Turn Pot Paused"
						},
						{
							"value": "10",
							"label": "Keep Warm"
						},
						{
							"value": "11",
							"label": "Keep Warm Paused"
						},
						{
							"value": "12",
							"label": "Keep Warm Completed"
						},
						{
							"value": "13",
							"label": "Crispy Roast"
						},
						{
							"value": "14",
							"label": "Degrease"
						}
					]
				},
				"refresh": true,
				"actions": [],
				"readmeComment": "Value mapping [\"0\"\u003d\"Off\",\"1\"\u003d\"Idle\",\"2\"\u003d\"Paused\",\"3\"\u003d\"Delay\",\"4\"\u003d\"Cooking\",\"5\"\u003d\"Preheat \",\"6\"\u003d\"Cooking Completed\",\"7\"\u003d\"Preheat Completed\",\"8\"\u003d\"Preheat Paused\",\"9\"\u003d\"Turn Pot Paused\",\"10\"\u003d\"Keep Warm\",\"11\"\u003d\"Keep Warm Paused\",\"12\"\u003d\"Keep Warm Completed\",\"13\"\u003d\"Crispy Roast\",\"14\"\u003d\"Degrease\"]"
			},
			{
				"property": "fault",
				"siid": 2,
				"piid": 2,
				"friendlyName": "Air Fryer - Device Fault",
				"channel": "fault",
				"type": "Number",
				"stateDescription": {
					"readOnly": true,
					"options": [
						{
							"value": "0",
							"label": "No Faults"
						},
						{
							"value": "1",
							"label": "E1"
						},
						{
							"value": "2",
							"label": "E2"
						},
						{
							"value": "3",
							"label": "E3"
						}
					]
				},
				"refresh": true,
				"actions": [],
				"readmeComment": "Value mapping [\"0\"\u003d\"No Faults\",\"1\"\u003d\"E1\",\"2\"\u003d\"E2\",\"3\"\u003d\"E3\"]"
			},
			{
				"property": "target-time",
				"siid": 2,
				"piid": 3,
				"friendlyName": "Air Fryer - Target Time",
				"channel": "target_time",
				"type": "Number:Time",
				"unit": "minutes",
				"stateDescription": {
					"minimum": 1,
					"maximum": 1440,
					"step": 1,
					"pattern": "%.0f %unit%"
				},
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "STRING"
					}
				]
			},
			{
				"property": "target-temperature",
				"siid": 2,
				"piid": 4,
				"friendlyName": "Air Fryer - Target Temperature",
				"channel": "target_temperature",
				"type": "Number:Temperature",
				"unit": "celsius",
				"stateDescription": {
					"minimum": 40,
					"maximum": 230,
					"step": 5,
					"pattern": "%.0f %unit%"
				},
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "NUMBER"
					}
				]
			},
			{
				"property": "left-time",
				"siid": 2,
				"piid": 5,
				"friendlyName": "Air Fryer - Left Time",
				"channel": "left_time",
				"type": "Number:Time",
				"unit": "minutes",
				"stateDescription": {
					"minimum": 0,
					"maximum": 1440,
					"step": 1,
					"pattern": "%.0f %unit%",
					"readOnly": true
				},
				"refresh": true,
				"actions": []
			},
			{
				"property": "auto-keep-warm",
				"siid": 2,
				"piid": 6,
				"friendlyName": "Air Fryer - Auto Keep Warm",
				"channel": "auto_keep_warm",
				"type": "Switch",
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "ONOFFBOOL"
					}
				]
			},
			{
				"property": "current-keep-warm",
				"siid": 2,
				"piid": 7,
				"friendlyName": "Air Fryer - Current Keep Warm",
				"channel": "current_keep_warm",
				"type": "Switch",
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "ONOFFBOOL"
					}
				]
			},
			{
				"property": "mode",
				"siid": 2,
				"piid": 8,
				"friendlyName": "Air Fryer - Mode",
				"channel": "mode",
				"type": "Number",
				"stateDescription": {
					"options": [
						{
							"value": "1",
							"label": "French Fries"
						},
						{
							"value": "2",
							"label": "Chicken Wing"
						},
						{
							"value": "3",
							"label": "Steak "
						},
						{
							"value": "4",
							"label": "Lamb Chops"
						},
						{
							"value": "5",
							"label": "Fish"
						},
						{
							"value": "6",
							"label": "Shrimp"
						},
						{
							"value": "7",
							"label": "Vegetables "
						},
						{
							"value": "8",
							"label": "Cake"
						},
						{
							"value": "9",
							"label": "Pizza"
						},
						{
							"value": "10",
							"label": "Defrost"
						},
						{
							"value": "11",
							"label": "Dried Fruit"
						},
						{
							"value": "12",
							"label": "Yogurt"
						},
						{
							"value": "0",
							"label": "Manual"
						}
					]
				},
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "NUMBER"
					}
				],
				"readmeComment": "Value mapping [\"1\"\u003d\"French Fries\",\"2\"\u003d\"Chicken Wing\",\"3\"\u003d\"Steak \",\"4\"\u003d\"Lamb Chops\",\"5\"\u003d\"Fish\",\"6\"\u003d\"Shrimp\",\"7\"\u003d\"Vegetables \",\"8\"\u003d\"Cake\",\"9\"\u003d\"Pizza\",\"10\"\u003d\"Defrost\",\"11\"\u003d\"Dried Fruit\",\"12\"\u003d\"Yogurt\",\"0\"\u003d\"Manual\"]"
			},
			{
				"property": "preheat",
				"siid": 2,
				"piid": 9,
				"friendlyName": "Air Fryer - Preheat",
				"channel": "preheat",
				"type": "Switch",
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "ONOFFBOOL"
					}
				]
			},
			{
				"property": "recipe-id",
				"siid": 2,
				"piid": 10,
				"friendlyName": "Air Fryer - Recipe Id",
				"channel": "recipe_id",
				"type": "String",
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "STRING"
					}
				]
			},
			{
				"property": "recipe-name",
				"siid": 2,
				"piid": 11,
				"friendlyName": "Air Fryer - Recipe Name",
				"channel": "recipe_name",
				"type": "String",
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "STRING"
					}
				]
			},
			{
				"property": "recipe-sync",
				"siid": 2,
				"piid": 12,
				"friendlyName": "Air Fryer - Recipe Sync",
				"channel": "recipe_sync",
				"type": "String",
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "STRING"
					}
				]
			},
			{
				"property": "target-cooking-measure",
				"siid": 2,
				"piid": 13,
				"friendlyName": "Air Fryer - Target Cooking Measure",
				"channel": "target_cooking_measure",
				"type": "Number:Dimensionless",
				"unit": "percentage",
				"stateDescription": {
					"options": [
						{
							"value": "0",
							"label": "NULL"
						},
						{
							"value": "1",
							"label": "One Layer"
						},
						{
							"value": "2",
							"label": "Double Layer"
						},
						{
							"value": "3",
							"label": "Half Pot"
						},
						{
							"value": "4",
							"label": "Full Pot"
						}
					]
				},
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "NUMBER"
					}
				],
				"readmeComment": "Value mapping [\"0\"\u003d\"NULL\",\"1\"\u003d\"One Layer\",\"2\"\u003d\"Double Layer\",\"3\"\u003d\"Half Pot\",\"4\"\u003d\"Full Pot\"]"
			},
			{
				"property": "turn-pot",
				"siid": 2,
				"piid": 14,
				"friendlyName": "Air Fryer - Turn Pot",
				"channel": "turn_pot",
				"type": "Number",
				"stateDescription": {
					"readOnly": true,
					"options": [
						{
							"value": "1",
							"label": "No Need Turn Over Pot"
						},
						{
							"value": "2",
							"label": "Need Turn Over Pot"
						}
					]
				},
				"refresh": true,
				"actions": [],
				"readmeComment": "Value mapping [\"1\"\u003d\"No Need Turn Over Pot\",\"2\"\u003d\"Need Turn Over Pot\"]"
			},
			{
				"property": "turn-pot-config",
				"siid": 2,
				"piid": 15,
				"friendlyName": "Air Fryer - Turn Pot Config",
				"channel": "turn_pot_config",
				"type": "Switch",
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "ONOFFBOOL"
					}
				]
			},
			{
				"property": "texture",
				"siid": 2,
				"piid": 16,
				"friendlyName": "Air Fryer - Texture",
				"channel": "texture",
				"type": "Number",
				"stateDescription": {
					"options": [
						{
							"value": "0",
							"label": "NONE"
						},
						{
							"value": "1",
							"label": "Crispy Roast"
						},
						{
							"value": "2",
							"label": "Tender Roast"
						},
						{
							"value": "3",
							"label": "Degrease"
						}
					]
				},
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "NUMBER"
					}
				],
				"readmeComment": "Value mapping [\"0\"\u003d\"NONE\",\"1\"\u003d\"Crispy Roast\",\"2\"\u003d\"Tender Roast\",\"3\"\u003d\"Degrease\"]"
			},
			{
				"property": "reservation-left-time",
				"siid": 2,
				"piid": 17,
				"friendlyName": "Air Fryer - Reservation Left Time",
				"channel": "reservation_left_time",
				"type": "Number:Time",
				"unit": "minutes",
				"stateDescription": {
					"minimum": 0,
					"maximum": 2880,
					"step": 1,
					"pattern": "%.0f %unit%"
				},
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "STRING"
					}
				]
			},
			{
				"property": "cooking-weight",
				"siid": 2,
				"piid": 18,
				"friendlyName": "Air Fryer - Cooking Weight",
				"channel": "cooking_weight",
				"type": "Number",
				"stateDescription": {
					"minimum": 100,
					"maximum": 1800,
					"step": 1,
					"pattern": "%.0f"
				},
				"refresh": true,
				"actions": [
					{
						"command": "set_properties",
						"parameterType": "STRING"
					}
				]
			}
		],
		"experimental": true
	}
}
Testing Properties:
status -> get_properties[{"did":"status","siid":2,"piid":1}] -> 38, 
fault -> get_properties[{"did":"fault","siid":2,"piid":2}] -> 39, 
target_time -> get_properties[{"did":"target-time","siid":2,"piid":3}] -> 40, 
target_temperature -> get_properties[{"did":"target-temperature","siid":2,"piid":4}] -> 41, 
left_time -> get_properties[{"did":"left-time","siid":2,"piid":5}] -> 42, 
auto_keep_warm -> get_properties[{"did":"auto-keep-warm","siid":2,"piid":6}] -> 43, 
current_keep_warm -> get_properties[{"did":"current-keep-warm","siid":2,"piid":7}] -> 44, 
mode -> get_properties[{"did":"mode","siid":2,"piid":8}] -> 45, 
preheat -> get_properties[{"did":"preheat","siid":2,"piid":9}] -> 46, 
recipe_id -> get_properties[{"did":"recipe-id","siid":2,"piid":10}] -> 47, 
recipe_name -> get_properties[{"did":"recipe-name","siid":2,"piid":11}] -> 48, 
recipe_sync -> get_properties[{"did":"recipe-sync","siid":2,"piid":12}] -> 49, 
target_cooking_measure -> get_properties[{"did":"target-cooking-measure","siid":2,"piid":13}] -> 50, 
turn_pot -> get_properties[{"did":"turn-pot","siid":2,"piid":14}] -> 51, 
turn_pot_config -> get_properties[{"did":"turn-pot-config","siid":2,"piid":15}] -> 52, 
texture -> get_properties[{"did":"texture","siid":2,"piid":16}] -> 53, 
reservation_left_time -> get_properties[{"did":"reservation-left-time","siid":2,"piid":17}] -> 54, 
cooking_weight -> get_properties[{"did":"cooking-weight","siid":2,"piid":18}] -> 55, 
```
