### ISSUE TITLE
[deconz] missing channel color_temperature

### ISSUE THREAD

**Issue by skylord73** [openhab/openhab-addons#18461]
## Expected Behavior

For devices of type `Extended color light` which report `"modes": ["ct", "hs", "xy"]` and have valid `ctmin`, `ctmax`, and `colorcapabilities`, the `color_temperature` channel should be exposed automatically as part of the discovered Thing and a new channel `brighness_ct` should be created in the deCONZ binding.

## Channel Behavior

The device (`GLEDOPTO GL-C-007P`) reports:

```json
{
  "capabilities": {
    "alerts": [
      "none",
      "select",
      "lselect"
    ],
    "color": {
      "ct": {
        "max": 500,
        "min": 158
      },
      "effects": [
        "none",
        "colorloop"
      ],
      "modes": [
        "ct",
        "hs",
        "xy"
      ]
    },
    "sleeper": false
  },
  "colorcapabilities": 31,
  "config": {
    "groups": [
      "0",
      "1",
      "2"
    ]
  },
  "ctmax": 500,
  "ctmin": 158,
  "ddf_hash": null,
  "ddf_policy": "latest_prefer_stable",
  "etag": "637a44b303a511d5b9279d5e01688d3d",
  "hascolor": true,
  "lastannounced": null,
  "lastseen": "2025-03-29T09:22Z",
  "manufacturername": "GLEDOPTO",
  "modelid": "GL-C-007P",
  "name": "Led Corridoio Notte",
  "nwkaddress": 7671,
  "state": {
    "alert": "none",
    "bri": 254,
    "colormode": "hs",
    "ct": 363,
    "effect": "none",
    "hue": 0,
    "on": true,
    "reachable": true,
    "sat": 254,
    "xy": [0, 0]
  },
  "swversion": "20241206",
  "type": "Extended color light",
  "uniqueid": "a4:c1:38:89:fb:f3:c5:a3-0b"
}
```
The generated Thing (via inbox discovery) has these code:
```yml
UID: deconz:extendedcolorlight:000000000000:a4c13889fbf3c5a30b
label: Phoscon Led Corridoio Notte
thingTypeUID: deconz:extendedcolorlight
configuration:
  lastSeenPolling: 1440
  id: "11"
bridgeUID: deconz:deconz:000000000000
location: Corridoio Notte
channels:
  - id: color
    channelTypeUID: system:color
    label: Color
    description: Controls the color of the light
    configuration: {}
  - id: color_temperature
    channelTypeUID: system:color-temperature-abs
    label: Color Temperature
    description: Controls the color temperature of the light in Kelvin
    configuration: {}
  - id: ontime
    channelTypeUID: deconz:ontime
    label: On Time
    description: Time that the light stays on before switched off automatically (0=forever)
    configuration: {}
  - id: alert
    channelTypeUID: deconz:alert
    label: Alert
    configuration: {}
  - id: effect
    channelTypeUID: deconz:effect
    label: Effect Channel
    configuration: {}
  - id: last_seen
    channelTypeUID: deconz:last_seen
    label: Last Seen
    description: The date and time when the sensor was last seen.
    configuration: {}

```
the UI has these channels:

- `color`
- `ontime`
- `alert`
- `effect`
- `last_seen`

But **the expected `color_temperature` channel is missing**, even though:

- The device is in `colormode: "ct"` at discovery time
- The capabilities clearly advertise support for `ct`

Creating a `Number` item manually linked to `...:color_temperature` **does work**, and returns Kelvin values correctly converted from the reported CT (e.g., `ct: 363` → `2755 K`). This confirms that the channel backend exists but is not exposed via UI or inbox Thing definition.

## Brighness Behavior

Even if the hidden color_temperature channel works, the brightness control is not behaving correctly.

deConz API exposes two different values of `state.bri` depending of `state.colormode`.
If `state.colormode : ct` the `state.bri` report the brightness of the White channel (W), while in `state.colormode : hs | xy` the brighness is referred to RGB channels.

This is working fine if you have a white lamp with temperature (no color), but if you have both RGB+CT, then the binding handles the RGB channell with brighness, CT with the hidden channel, but not the CT brightness.

The results is the brigthness value in Color, depends on the last action, if you change che color it is the right one, if you change the temperature it is the W channel brightness

## Possible Solution

When object has CT and others channels, create a kind of `Followup` between the two `state.bri`:
- when brightness is changed in RGB channels:
```json
 {state.colormode: hs|xy, state.bri <value>}
 ```
a second command shold be executed to change the one in CT channels with the same value:
```json
{state.colormode: ct, state.bri <value>}
```
and viceversa.
this maintain compatibility with HomeKit that has only one brightness for color and temperature

## Steps to Reproduce (for Bugs)

1. Create GLEDOPTO GL-C-007P or GL-G-004P in deCONZ/Phoscon
2. Discover the Thing from OpenHAB inbox
3. Observe that the channel `color_temperature` is missing
4. Link an item manually to the expected UID `...:color_temperature` and observe that it works correctly

## Context

I'm trying to control both color and white brightness of the GL-C-007P or GL-G-004P via OpenHAB. The inability to access the `color_temperature` channel from the UI complicates both automation and HomeKit integration.

## Your Environment

- Version used: openHAB 4.3.3 (Main UI Commit 1cc0b830)
- Add-on: org.openhab.binding.deconz (latest from addons 4.3)
- Environment name and version: Java 17, DSM 7.2 (Synology)
- Operating System: Linux (Synology NAS)

**Comment by andrewfg** [comment]
@skylord73 sorry for a maybe silly question, but did you check "Show Advanced" ??

![Image](https://github.com/user-attachments/assets/9d3f3ccb-6e89-4b26-a732-cfe688ef7db5)

**Comment by andrewfg** [comment]
> This is working fine if you have a white lamp with temperature (no color), but if you have both RGB+CT, then the binding handles the RGB channell with brighness, CT with the hidden channel, but not the CT brightness.

> The results is the brigthness value in Color, depends on the last action, if you change che color it is the right one, if you change the temperature it is the W channel brightness

Yeah. I have seen this in other bindings.

I suspect the issue is due to the way the in OH we are "munging" both the color and the brightness (and indeed the on/off state) into a single HSBType channel. The HS part codes the color, and the B part codes the brightness (and on/off depending on if B==0 or not). i.e. we have three state vectors munged into one channel; and if the device supports a CT channel then we have 4 state vectors munged into two channels.

By contrast the device API has (probably) four orthogonal and quite independent state vectors. For this reason I am by far not a fan of the OH munged model. I have had extensive discussions with OH maintainers on this, but was overruled. But therefore I am probably the world's expert in un-munging light channels. So I am on your case.

@skylord73 I don't actually have any deconz hardware so to fix this, I will need you help in testing. I would make a number of trial Jars and ask you to test in an iterative process until we get the correct solution. Is that Ok with you?

**Comment by skylord73** [comment]
Thank you for your time.
Feel free to send me code to test, but use andrea.bignozzi@gmail.com.

Yes you are right, the missing channel was inside the advanced options :) sorry!  
I tried to link a Dimmer to the Color channel, but it asked me for a conversion Profile, but I don't think is the right way to proceed.  
Let me try to explain you how the deConz/Phoscon API works when you have a Light with RGB+W.  
In this situation deconz configure at least two colormode: ct and xy|hs each one with his own bri attribute.

## Sending commands

When you want to change the RGB values you:
`curl -X PUT http://192.168.20.2:8090/api/xxxxx/lights/11/state -H "Content-Type: application/json" -d "{\"on\":true,\"bri\":128, \"colormode\":\"xy\",\"xy\":[0.5,0.5]}"`

```json
17:49:00.960 [TRACE] [internal.netutils.WebSocketConnection] - Websocket$1743020543748-1 received raw data: {"e":"changed","id":"11","r":"lights","state":{"alert":"none","bri":254,"colormode":"xy","ct":158,"effect":"none","hue":0,"on":true,"reachable":true,"sat":254,"xy":[0.5,0.5]},"t":"event","uniqueid":"a4:c1:38:89:fb:f3:c5:a3-0b"}

17:49:00.962 [TRACE] [nz.internal.handler.LightThingHandler] - deconz:extendedcolorlight:000000000000:a4c13889fbf3c5a30b received LightMessage{hascolor=null, ctmax=null, ctmin=null, type=null, state=LightState{reachable=true, on=true, bri=254, alert='none', colormode='xy', effect='none', effectSpeed=null, ontime=null, hue=0, sat=254, ct=158, xy=[0.5, 0.5], transitiontime=null}, e='changed', r='LIGHTS', t='event', id='11', manufacturername='', modelid='', name='', swversion='', ep='', uniqueid='a4:c1:38:89:fb:f3:c5:a3-0b'} 
```
and as output the RGB led in the light get the right `color` and `brightness`.

If you want to change the CT you:

`curl -X PUT http://192.168.20.2:8090/api/xxxxx/lights/11/state -H "Content-Type: application/json" -d "{\"on\":true,\"bri\":128, \"colormode\":\"ct\",\"ct\":158}"`

```json
17:40:44.738 [TRACE] [internal.netutils.WebSocketConnection] - Websocket$1743020543748-1 received raw data: {"e":"changed","id":"11","r":"lights","state":{"alert":"none","bri":128,"colormode":"ct","ct":158,"effect":"none","hue":0,"on":true,"reachable":true,"sat":254,"xy":[0,0]},"t":"event","uniqueid":"a4:c1:38:89:fb:f3:c5:a3-0b"}

17:40:44.739 [TRACE] [nz.internal.handler.LightThingHandler] - deconz:extendedcolorlight:000000000000:a4c13889fbf3c5a30b received LightMessage{hascolor=null, ctmax=null, ctmin=null, type=null, state=LightState{reachable=true, on=true, bri=128, alert='none', colormode='ct', effect='none', effectSpeed=null, ontime=null, hue=0, sat=254, ct=158, xy=[0.0, 0.0], transitiontime=null}, e='changed', r='LIGHTS', t='event', id='11', manufacturername='', modelid='', name='', swversion='', ep='', uniqueid='a4:c1:38:89:fb:f3:c5:a3-0b'}
```

and as output the RGB lights are configured as cold white (R, G, B same intesity) and with the warm white led, balacing the brightnes to obtain the desired color temperature.

Now that we have sent the two commands above, in the same order the log from the binding is:
```json
18:00:42.663 [TRACE] [internal.netutils.WebSocketConnection] - Websocket$1743020543748-1 received raw data: {"attr":{"ddf_hash":null,"ddf_policy":"latest_prefer_stable","lastannounced":null,"lastseen":"2025-03-29T17:00Z","manufacturername":"GLEDOPTO","modelid":"GL-C-007P","name":"Led Corridoio Notte","nwkaddress":7671,"swversion":"20241206","type":"Extended color light","uniqueid":"a4:c1:38:89:fb:f3:c5:a3-0b"},"e":"changed","id":"11","r":"lights","t":"event","uniqueid":"a4:c1:38:89:fb:f3:c5:a3-0b"}

18:00:42.665 [TRACE] [nz.internal.handler.LightThingHandler] - deconz:extendedcolorlight:000000000000:a4c13889fbf3c5a30b received LightMessage{hascolor=null, ctmax=null, ctmin=null, type=null, state=null, e='changed', r='LIGHTS', t='event', id='11', manufacturername='', modelid='', name='', swversion='', ep='', uniqueid='a4:c1:38:89:fb:f3:c5:a3-0b'}

```

there are no state updates, only a kind of lastseen update i think.

## Things: Color Temperature (CT)

I create a new manual Things from the binding:
```yml
UID: deconz:colortemperaturelight:000000000000:48024822d6
label: Phoscon Led Corridoio Notte CT
thingTypeUID: deconz:colortemperaturelight
configuration:
  lastSeenPolling: 1440
  id: "11"
bridgeUID: deconz:deconz:000000000000
location: Corridoio Notte
channels:
  - id: brightness
    channelTypeUID: system:brightness
    label: Brightness
    description: Controls the brightness and switches the light on and off
    configuration: {}
  - id: color_temperature
    channelTypeUID: system:color-temperature-abs
    label: Color Temperature
    description: Controls the color temperature of the light in Kelvin
    configuration: {}
  - id: ontime
    channelTypeUID: deconz:ontime
    label: On Time
    description: Time that the light stays on before switched off automatically (0=forever)
    configuration: {}
  - id: alert
    channelTypeUID: deconz:alert
    label: Alert
    configuration: {}
  - id: effect
    channelTypeUID: deconz:effect
    label: Effect Channel
    configuration: {}
  - id: last_seen
    channelTypeUID: deconz:last_seen
    label: Last Seen
    description: The date and time when the sensor was last seen.
    configuration: {}
```
and add items connected to the Color Temperature and Brightness

```yml
label: Phoscon Led Corridoio Notte CT
type: Number:Temperature
category: ColorLight
groupNames:
  - gLedCorridoioNotteCT
tags:
  - Control
  - ColorTemperature
```
and

```yml
label: Phoscon Led Corridoio Notte CT Brightness
type: Dimmer
category: Light
groupNames:
  - gLedCorridoioNotteCT
tags:
  - Light
  - Control
```
### Brightness

#### Test
If I try to change the brightness with the new object:
```json
19:23:54.296 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Phoscon_Led_Corridoio_Notte_CT_Brightness' changed from 80 to 20

19:23:54.299 [TRACE] [.internal.handler.DeconzBridgeHandler] - Sending {"on":true,"bri":50} via PUT to http://172.18.0.16:8090/api/33A77F5F12/lights/11/state

19:23:54.301 [TRACE] [ternal.handler.DeconzBaseThingHandler] - Result code=200, body=[{"success":{"/lights/11/state/on":true}},{"success":{"/lights/11/state/bri":50}}]

19:23:54.303 [TRACE] [internal.netutils.WebSocketConnection] - Websocket$1743020543748-1 received raw data: {"e":"changed","id":"11","r":"lights","state":{"alert":"none","bri":50,"colormode":"xy","ct":500,"effect":"none","hue":0,"on":true,"reachable":true,"sat":254,"xy":[0.163,0.3292]},"t":"event","uniqueid":"a4:c1:38:89:fb:f3:c5:a3-0b"}

19:23:54.304 [TRACE] [nz.internal.handler.LightThingHandler] - deconz:extendedcolorlight:000000000000:a4c13889fbf3c5a30b received LightMessage{hascolor=null, ctmax=null, ctmin=null, type=null, state=LightState{reachable=true, on=true, bri=50, alert='none', colormode='xy', effect='none', effectSpeed=null, ontime=null, hue=0, sat=254, ct=500, xy=[0.163, 0.3292], transitiontime=null}, e='changed', r='LIGHTS', t='event', id='11', manufacturername='', modelid='', name='', swversion='', ep='', uniqueid='a4:c1:38:89:fb:f3:c5:a3-0b'}

19:23:54.311 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Phoscon_Led_Corridoio_Notte_Colore_Color' changed from 182.5261,75.44300,100.00 to 182.5251,78.37000,57.333
```
as you can see the Items sends: `{"on":true,"bri":50}` without forcing the `colormode:ct`and the effect is the changing of the brightnes of the Color Item : 
```json
'Phoscon_Led_Corridoio_Notte_Colore_Color' changed from 182.5261,75.44300,**100.00** to 182.5251,78.37000,**57.333**
```
#### Solution
Force the right colormode sending ct:<current_value>, it should work also for CT only lamps and fix the problem with the RGB+CT ones

### Color Temperature
#### Test
If I change the color temperature:
```json
19:36:36.688 [INFO ] [openhab.event.ItemCommandEvent       ] - Item 'Phoscon_Led_Corridoio_Notte_CT_Color_Temperature' received command 6300

19:36:36.689 [INFO ] [openhab.event.ItemStatePredictedEvent] - Item 'Phoscon_Led_Corridoio_Notte_CT_Color_Temperature' predicted to become 6300

19:36:36.690 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Phoscon_Led_Corridoio_Notte_CT_Color_Temperature' changed from 2000 K to 6300 K

19:36:36.691 [TRACE] [DeconzDynamicStateDescriptionProvider] - returning new stateDescription for deconz:colortemperaturelight:000000000000:48024822d6:color_temperature

19:36:36.698 [TRACE] [.internal.handler.DeconzBridgeHandler] - Sending {"on":true,"ct":158} via PUT to http://172.18.0.16:8090/api/33A77F5F12/lights/11/state

19:36:36.701 [TRACE] [ternal.handler.DeconzBaseThingHandler] - Result code=200, body=[{"success":{"/lights/11/state/on":true}},{"success":{"/lights/11/state/ct":158}}]

19:36:36.701 [TRACE] [internal.netutils.WebSocketConnection] - Websocket$1743020543748-1 received raw data: {"e":"changed","id":"11","r":"lights","state":{"alert":"none","bri":101,"colormode":"ct","ct":158,"effect":"none","hue":0,"on":true,"reachable":true,"sat":254,"xy":[0,0]},"t":"event","uniqueid":"a4:c1:38:89:fb:f3:c5:a3-0b"}

19:36:36.703 [TRACE] [nz.internal.handler.LightThingHandler] - deconz:extendedcolorlight:000000000000:a4c13889fbf3c5a30b received LightMessage{hascolor=null, ctmax=null, ctmin=null, type=null, state=LightState{reachable=true, on=true, bri=101, alert='none', colormode='ct', effect='none', effectSpeed=null, ontime=null, hue=0, sat=254, ct=158, xy=[0.0, 0.0], transitiontime=null}, e='changed', r='LIGHTS', t='event', id='11', manufacturername='', modelid='', name='', swversion='', ep='', uniqueid='a4:c1:38:89:fb:f3:c5:a3-0b'}
```
Now you send `{"on":true,"ct":158}` and the colormode changed to `ct` (sending ct force the colormode=ct). If now I change the brightness every thing is working fine, because the `colormode` is the right one

## Things: Color (RGB)
I create an automatic Things 
```yml
UID: deconz:extendedcolorlight:000000000000:a4c13889fbf3c5a30b
label: Phoscon Led Corridoio Notte Colore
thingTypeUID: deconz:extendedcolorlight
configuration:
  lastSeenPolling: 1440
  id: "11"
bridgeUID: deconz:deconz:000000000000
location: Corridoio Notte
channels:
  - id: color
    channelTypeUID: system:color
    label: Color
    description: Controls the color of the light
    configuration: {}
  - id: color_temperature
    channelTypeUID: system:color-temperature-abs
    label: Color Temperature
    description: Controls the color temperature of the light in Kelvin
    configuration: {}
  - id: ontime
    channelTypeUID: deconz:ontime
    label: On Time
    description: Time that the light stays on before switched off automatically (0=forever)
    configuration: {}
  - id: alert
    channelTypeUID: deconz:alert
    label: Alert
    configuration: {}
  - id: effect
    channelTypeUID: deconz:effect
    label: Effect Channel
    configuration: {}
  - id: last_seen
    channelTypeUID: deconz:last_seen
    label: Last Seen
    description: The date and time when the sensor was last seen.
    configuration: {}
```
and an Item
```yml
label: Phoscon Led Corridoio Notte Colore Color
type: Color
category: ColorLight
groupNames:
  - gLedCorridoioNotte
tags:
  - Light
  - Control
```
### Test
If I cange color, or everything else

```json
20:13:01.563 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Phoscon_Led_Corridoio_Notte_Colore_Color' changed from 0.0,100,100 to 248,100,100

20:13:01.563 [TRACE] [.internal.handler.DeconzBridgeHandler] - Sending {"on":true,"bri":254,"xy":[0.14258342345687247,0.04312907884209485]} via PUT to http://172.18.0.16:8090/api/33A77F5F12/lights/11/state

20:13:01.567 [TRACE] [ternal.handler.DeconzBaseThingHandler] - Result code=200, body=[{"success":{"/lights/11/state/on":true}},{"success":{"/lights/11/state/bri":254}},{"success":{"/lights/11/state/xy":[0.14258342345687247,0.04312907884209485]}}]

20:13:01.568 [TRACE] [internal.netutils.WebSocketConnection] - Websocket$1743020543748-1 received raw data: {"e":"changed","id":"11","r":"lights","state":{"alert":"none","bri":254,"colormode":"xy","ct":158,"effect":"none","hue":0,"on":true,"reachable":true,"sat":254,"xy":[0.1426,0.0431]},"t":"event","uniqueid":"a4:c1:38:89:fb:f3:c5:a3-0b"}

20:13:01.570 [TRACE] [nz.internal.handler.LightThingHandler] - deconz:extendedcolorlight:000000000000:a4c13889fbf3c5a30b received LightMessage{hascolor=null, ctmax=null, ctmin=null, type=null, state=LightState{reachable=true, on=true, bri=254, alert='none', colormode='xy', effect='none', effectSpeed=null, ontime=null, hue=0, sat=254, ct=158, xy=[0.1426, 0.0431], transitiontime=null}, e='changed', r='LIGHTS', t='event', id='11', manufacturername='', modelid='', name='', swversion='', ep='', uniqueid='a4:c1:38:89:fb:f3:c5:a3-0b'}
```
and the behavior is as aspected.

## Problem
In mixed situation, when the lamp is RGB+CT or RGBW and has multiple `colormode = ct | xy | hs` the brighness control depends on the last colormode so you cannot use the brighness control of the `deconz:colortemperaturelight` and if you use the brightness of the 
`deconz:extendedcolorlight` that sends the whole HSB array, the colormode is resetted to xy | hs moving light from CT to RGB.

## Solution
### Brightness bug
Solve the CT brightness problem forcing `ct:<current_value>` in update json, so in mixed situation you can configure two different lights one for RGB and one for CT.
### RGBW/RGB+CT Lamp
If you use HomeKit or other framework whith complex lights, for a RGBW/RGB+CT light you need:
- Lighting.OnState
- Lighting.Brightness
- Lighting.ColorTemperature
- Lighting.Hue
- Lighting.Saturation  

so the first think I'll do is to add the missing channels:  
- Switch:OnState `{on:<value>}`
- Number:Brightness_ct `{"on":bri==0?false:true,"bri":<value>, "ct":<current_value>}`
- Number:Brightness_color `{"on":bri==0?false:true,"bri":<value>, "xy|hs":<current_value>}`
- Number:Hue `{"hue|xy":<value>}`
- Number:Saturation `{"sat":<value>}`  

Should be usefull to add the on: value to false when bri=0 because I notice that when you PUT bri=0, the deconz API return bri=2, so the automatic switch off for bri=0 does not work.
```
X:\andrea.bignozzi>curl -X PUT http://192.168.20.2:8090/api/xxxxxxxxx/lights/11/state -H Content-Type: application/json" -d "{\"on\":true, \"bri\":0, \"xy\":[0.2,0.6]}" 
[{"success":{"/lights/11/state/on":true}},{"success":{"/lights/11/state/bri":0}},{"success":{"/lights/11/state/xy":[0.2,0.6]}}]
```

```json
21:21:23.315 [TRACE] [internal.netutils.WebSocketConnection] - Websocket$1743020543748-1 received raw data: {"e":"changed","id":"11","r":"lights","state":{"alert":"none","bri":0,"colormode":"xy","ct":500,"effect":"none","hue":0,"on":true,"reachable":true,"sat":254,"xy":[0.2,0.6]},"t":"event","uniqueid":"a4:c1:38:89:fb:f3:c5:a3-0b"}

21:21:23.317 [TRACE] [nz.internal.handler.LightThingHandler] - deconz:extendedcolorlight:000000000000:a4c13889fbf3c5a30b received LightMessage{hascolor=null, ctmax=null, ctmin=null, type=null, state=LightState{reachable=true, on=true, bri=0, alert='none', colormode='xy', effect='none', effectSpeed=null, ontime=null, hue=0, sat=254, ct=500, xy=[0.2, 0.6], transitiontime=null}, e='changed', r='LIGHTS', t='event', id='11', manufacturername='', modelid='', name='', swversion='', ep='', uniqueid='a4:c1:38:89:fb:f3:c5:a3-0b'}
```
```json
but if I check the deconz API:
"state": {
    "alert": "none",
    "bri": 2,
    "colormode": "xy",
    "ct": 500,
    "effect": "none",
    "hue": 0,
    "on": true,
    "reachable": true,
    "sat": 254,
    "xy": [0.2, 0.6]
  },
```
The deConz API does not support changing colormode parameter, you can force the change sending a xy|hs|ct:<value>, so to solve the brightness problem you need to update also che ct|xy|hs value whith the current_value to fake the system.

### Whishlist
To have a number:Brightness, thas updates boths ct and xy|hs bri (neet to send two different update PUT)
