### ISSUE TITLE
[mqtt.homeassistant] Link between item and channel is deleted after OH restart or after changing a "label"

### ISSUE THREAD

**Issue by miwok72** [openhab/openhab-addons#18494]
I've reported and described the issue here:

https://community.openhab.org/t/zwave-js-ui-in-place-of-oh-zwave-binding/150007/147?u=miwok

similar problem:  https://github.com/openhab/openhab-addons/issues/18278

The error is easily reproducible by changing a label or restarting OH.

I'm using zwave-js-ui and mqtt.homeassistant auto discovery.

```
runtimeInfo:
  version: 4.3.4
  buildString: Release Build
locale: de-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.14
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu17.56+15-CA
  osName: Linux
  osVersion: 5.15.0-136-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 124528192
  totalMemory: 688914432
  uptime: 192854
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-airquality
  - binding-androidtv
  - binding-astro
  - binding-avmfritz
  - binding-chromecast
  - binding-exec
  - binding-fineoffsetweatherstation
  - binding-fronius
  - binding-homematic
  - binding-icalendar
  - binding-ipcamera
  - binding-ipp
  - binding-jeelink
  - binding-logreader
  - binding-mail
  - binding-modbus
  - binding-mqtt
  - binding-network
  - binding-networkupstools
  - binding-ntp
  - binding-openweathermap
  - binding-snmp
  - binding-systeminfo
  - binding-telegram
  - binding-tr064
  - binding-upnpcontrol
  - persistence-influxdb
  - persistence-mapdb
  - transformation-exec
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - ui-basic
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de-AT
    languages:
      - de-AT
      - de
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: geras
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/135.0.0.0 Safari/537.36
timestamp: 2025-04-06T11:17:45.330Z
```
