### ISSUE TITLE
[automower] Migrate Automower Bundle from REST API to WebSocket API

### ISSUE THREAD

**Issue by MikeTheTux** [openhab/openhab-addons#18574]
### Issue: Migrate Automower Bundle from REST API to WebSocket API

**Description:**
The current Automower bundle in openHAB uses the REST API to communicate with Husqvarna's Automower Connect API. However, Husqvarna provides a WebSocket API that offers status updates in real-time. This issue proposes migrating the Automower bundle (status updates) from the REST API to the WebSocket API. Currently the WebSocket does not support sending control commands to the mower. For this the REST API is still required.

**Benefits of Using the WebSocket API:**
1. **Real-Time Updates:**
   - The WebSocket API provides real-time updates for mower status, eliminating the need for periodic polling.
   - This ensures faster response times and more accurate state representation in openHAB.

3. **Enhanced User Experience:**
   - Real-time updates improve the user experience by providing immediate feedback on mower actions and status changes.
   - This is particularly useful for time-sensitive operations like starting, stopping, or scheduling tasks as well as position updates.

2. **Reduced Network Overhead:**
   - Unlike REST, which requires frequent HTTP requests to fetch updates, WebSocket maintains a persistent connection.
   - This reduces the number of HTTP requests, lowering bandwidth usage and server load.

**Proposed Changes:**
- Replace the current REST-based implementation with WebSocket-based communication.
- Implement a WebSocket client in the Automower bundle to handle real-time updates.
- Keep REST API for sending control commands
- Update documentation to reflect the new WebSocket-based setup.

**References:**
- Husqvarna Automower Connect API Documentation: [https://developer.husqvarnagroup.cloud/apis/automower-connect-api](https://developer.husqvarnagroup.cloud/apis/automower-connect-api)

**Impact:**
This change will significantly enhance the Automower integration in openHAB, providing users with a more responsive and efficient experience. It will also position openHAB as a modern and forward-looking platform for smart home automation.

**Request for Feedback:**
Community feedback is requested on the feasibility, potential challenges, and any additional features that could be included in this migration.

**Comment by MikeTheTux** [comment]
Created the following Automower WSS -> MQTT bridge as interim solution:

```
const mqtt = require('mqtt');
const WebSocket = require('ws');


// MQTT settings
const MQTT_BROKER_URL = 'mqtt://localhost:1883';
const MQTT_TOPIC = 'automower';
const MQTT_PASSWORD = 'yyy';

// Husqvarna Automower Connect WebSocket endpoint
const WEBSOCKET_URL = 'wss://ws.openapi.husqvarna.dev/v1';
// OAuth2 access token (get this via REST API)
const ACCESS_TOKEN = 'xxx';

// Connect to MQTT broker
const mqttClient  = mqtt.connect(MQTT_BROKER_URL, {
   username: 'openhabian',
   password: MQTT_PASSWORD,
   clientId: 'mqttjs_' + Math.random().toString(16).slice(2, 10),
   will: {
      topic: `${MQTT_TOPIC}/bridge/availability`,
      payload: 'offline',
      qos: 1,
      retain: true
   }
});

mqttClient.on('connect', function () {
    console.log('Connected to MQTT broker');
});

// Helper to track mower availability
const mowerAvailability = {};

// Connect to Husqvarna WebSocket API
const ws = new WebSocket(WEBSOCKET_URL, {
    headers: {
        'Authorization': `Bearer ${ACCESS_TOKEN}`
    }
});

ws.on('open', () => {
    console.log('Connected to Husqvarna WebSocket');
    mqttClient.publish(`${MQTT_TOPIC}/bridge/availability`, 'online', {retain: true});
    // Subscribe to all mower events
    ws.send(JSON.stringify({
        "type": "subscribe",
        "attributes": {
            "categories": ["*"]
        }
    }));
    // Set all known mowers to online (if any known)
    Object.keys(mowerAvailability).forEach(mowerId => {
        mqttClient.publish(`${MQTT_TOPIC}/${mowerId}/availability`, 'online', {retain: true});
    });
});

ws.on('message', (data) => {
    console.log('Received from WebSocket:', data.toString());
    try {
        const msg = JSON.parse(data);
        const mowerId = msg.id || 'unknown';
        const eventType = msg.type || 'unknown';
        const topic = `${MQTT_TOPIC}/${mowerId}/${eventType}`;
        const attributes = msg.attributes ? JSON.stringify(msg.attributes) : '{}';
        mqttClient.publish(topic, attributes);
        // Publish availability for this mower
        if (!mowerAvailability[mowerId]) {
            mowerAvailability[mowerId] = true;
            mqttClient.publish(`${MQTT_TOPIC}/${mowerId}/availability`, 'online', {retain: true});
        }
    } catch (e) {
        console.error('Failed to parse WebSocket message:', e);
        mqttClient.publish('${MQTT_TOPIC}/unknown/unknown', data.toString());
    }
});

ws.on('close', () => {
    console.log('WebSocket connection closed');
    mqttClient.publish(`${MQTT_TOPIC}/bridge/availability`, 'offline', {retain: true});
    // Set all known mowers to offline
    Object.keys(mowerAvailability).forEach(mowerId => {
        mqttClient.publish(`${MQTT_TOPIC}/${mowerId}/availability`, 'offline', {retain: true});
    });
});

ws.on('error', (err) => {
    console.error('WebSocket error:', err);
});
```

Using the following generic MQTT thing, selected items from the mower can be updated in real-time (not bound to the polling of the binding):

```
UID: mqtt:topic:2d35f74500:3e39259062
label: Husqvarna Automower® 430X NERA MQTT
thingTypeUID: mqtt:topic
configuration:
  payloadNotAvailable: offline
  availabilityTopic: automower/bridge/availability
  payloadAvailable: online
bridgeUID: mqtt:broker:2d35f74500
channels:
  - id: position
    channelTypeUID: mqtt:location
    label: Position
    description: ""
    configuration:
      formatBeforePublish: "%s"
      stateTopic: automower/34862665-5743-4a88-9032-244be8bdaeff/position-event-v2
      transformationPattern:
        - JS(positionToLocation.js)
  - id: battery
    channelTypeUID: mqtt:number
    label: Battery
    description: ""
    configuration:
      stateTopic: automower/34862665-5743-4a88-9032-244be8bdaeff/battery-event-v2
      transformationPattern:
        - JSONPATH($.battery.batteryPercent)
      unit: "%"
  - id: activity
    channelTypeUID: mqtt:string
    label: Activity
    description: ""
    configuration:
      stateTopic: automower/34862665-5743-4a88-9032-244be8bdaeff/mower-event-v2
      transformationPattern:
        - JSONPATH($.mower.activity)
```
