### ISSUE TITLE
[MQTT] homie temp/humidity sensor gets wrong units after upgrade from 3.4.2 to 4.3.4

### ISSUE THREAD

**Issue by joelmr123** [openhab/openhab-addons#18606]
I have five temperature sensors connected to a Raspberry pi. Three of them provide only temperature, and the other two provide temperature and humidity. I’m using the [GitHub - mjcumming/Homie4: Python package for Homie v4 specification](https://github.com/mjcumming/homie4) python library to read the values and publish them to mqtt. In Openhab 3, the Things that get created for all five sensors have the statuses that are unitless Numbers. For instance:

![Image](https://github.com/user-attachments/assets/62571ae4-c7dd-4a3c-b85e-a0127d509ee2)

After upgrading to Openhab 4, the Things created for objects that only supply temperature show the sensor status as Numbers with a unit of Temperature:

![Image](https://github.com/user-attachments/assets/27a8f240-0509-4253-9a9e-1dc9faaf3b3d)

However, the Things created for objects that supply both temperature and humidity show the temperature status as a Number with a unit of ElectricCapacitance:

![Image](https://github.com/user-attachments/assets/d0c387da-840b-439f-bdcd-05eaa00c1cad)

When I snoop on the mqtt bus, both types of sensors seem to be identical as far as temperature reporting goes - both report temperature units as “F”:

(a temperature-only sensor)
homie/ts-226/status/temperature/$unit F

(a temp/humid sensor)
homie/temphumid2/status/temperature/$unit F

Interestingly, according to [Units Of Measurement | openHAB](https://www.openhab.org/docs/concepts/units-of-measurement.html), a unit of “F” is actually a Farad, the unit of capacitance. It’s “°F”, with the degree thingee in front of the F, that’s the unit for temperature (in Fahrenheit). Why would one type of Thing get the units right, and the other get it wrong?

I have been able to work around this issue by manually creating a generic MQTT Thing, see below, but I'd rather not have to do that.

```
UID: mqtt:topic:6971972117
label: temphumid1manual
thingTypeUID: mqtt:topic
configuration: {}
bridgeUID: mqtt:broker:98602dd68d
channels:
  - id: temperature
    channelTypeUID: mqtt:number
    label: temperature
    description: temperature
    configuration:
      unit: °F
      min: -100
      stateTopic: homie/temphumid1/status/temperature
      max: 400
  - id: humidity
    channelTypeUID: mqtt:number
    label: humidity
    description: humidity
    configuration:
      unit: "%"
      min: 0
      stateTopic: homie/temphumid1/status/humidity
      max: 100
```
