### ISSUE TITLE
[rfxcom] Working OH2 setup stopped working

### ISSUE THREAD

**Issue by RastaChaum** [openhab/openhab-addons#6964]
Hello everybody !
See me issue below...

## Expected Behavior
Thing RFXCOM must be online

## Current Behavior
I have the same issue thant @stefaav for few days with RfxCom.
His issue was the #3321 
But it was close without solution/explaination.

## Context
The difference for me is that :
    i haven't MySensors
    i run OH 2.5.0 with Docker

To resume, when OH start, RFXCOM works fine during few minutes. And quickly, it beeing offline.
See this trace to understand :

2020-01-23 19:21:27.712 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-misc-restdocs'
2020-01-23 19:21:28.994 [INFO ] [internal.handler.RFXComBridgeHandler] - RFXCOM transceiver/receiver type: _433_92MHZ_TRANSCEIVER, hw version: 0.1, fw version: 25
2020-01-23 19:21:30.614 [INFO ] [smarthome.model.script.rullershutter] - One item for RullerShutter programming has been updated : calculating new timers
2020-01-23 19:21:30.917 [INFO ] [smarthome.model.script.rullershutter] - Shutters for day area will open at 08:00:00.000
2020-01-23 19:21:30.940 [INFO ] [smarthome.model.script.rullershutter] - Shutters for day area will close at 23:00:00.000
2020-01-23 19:21:30.962 [INFO ] [smarthome.model.script.rullershutter] - Shutters for night area will open at 08:00:00.000
2020-01-23 19:21:30.987 [INFO ] [smarthome.model.script.rullershutter] - Shutters for night area will close at 21:00:00.000
2020-01-23 19:22:23.524 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-misc-restdocs'
2020-01-23 19:23:26.757 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-misc-restdocs'
2020-01-23 19:23:27.894 [INFO ] [internal.handler.RFXComBridgeHandler] - RFXCOM transceiver/receiver type: _433_92MHZ_TRANSCEIVER, hw version: 0.1, fw version: 25
2020-01-23 19:24:22.969 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-misc-restdocs'
2020-01-23 19:25:23.746 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-misc-restdocs'
2020-01-23 19:25:25.232 [INFO ] [internal.handler.RFXComBridgeHandler] - RFXCOM transceiver/receiver type: _433_92MHZ_TRANSCEIVER, hw version: 0.1, fw version: 25
2020-01-23 19:26:26.205 [INFO ] [internal.handler.RFXComBridgeHandler] - RFXCOM transceiver/receiver type: _433_92MHZ_TRANSCEIVER, hw version: 0.1, fw version: 25
2020-01-23 19:26:26.250 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler RFXComBridgeHandler tried updating the thing status although the handler was already disposed.
2020-01-23 19:26:27.119 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-misc-restdocs'
2020-01-23 19:26:29.666 [ERROR] [internal.handler.RFXComBridgeHandler] - Connection to RFXCOM transceiver failed
org.eclipse.smarthome.io.transport.serial.PortInUseException: null
at org.eclipse.smarthome.io.transport.serial.internal.SerialPortIdentifierImpl.open(SerialPortIdentifierImpl.java:61) ~[?:?]
at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector.connect(RFXComSerialConnector.java:61) ~[?:?]
at org.openhab.binding.rfxcom.internal.handler.RFXComBridgeHandler.connect(RFXComBridgeHandler.java:188) ~[?:?]
at org.openhab.binding.rfxcom.internal.handler.RFXComBridgeHandler.lambda$0(RFXComBridgeHandler.java:162) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_232]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by RastaChaum** [comment]
Extract of my compose file 
```

  openhab:
    image: openhab/openhab:2.5.0-armhf-debian
    restart: unless-stopped
    network_mode: host
    container_name: openhab
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/openhab/addons:/openhab/addons
      - /opt/openhab/conf:/openhab/conf
      - /opt/openhab/userdata:/openhab/userdata
    environment:
      OPENHAB_HTTP_PORT: '8080'
      OPENHAB_HTTPS_PORT: '8443'
      LC_ALL: 'fr_FR.UTF-8'
      LANG: 'fr_FR.UTF-8'
      LANGUAGE: 'fr_FR.UTF-8'
      EXTRA_JAVA_OPTS: '-Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0 -Duser.timezone=Europe/Paris' 
      USER_ID: 9001
      GROUP_ID: 1000
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - "8443:8443"
      - "5007:5007"
```
