### ISSUE TITLE
[mqtt] System Broker not Working with IPv4 address

### ISSUE THREAD

**Issue by SMeatBoy** [openhab/openhab-addons#9140]
## Expected Behavior

Configuring the MQTT system broker connection via PaperUI with an IPv4 address should lead to a connection with the specified broker running on the system, e.g at `10.0.0.10:1883`. 

## Current Behavior
Configuring the MQTT system broker with an IPV4 address leads to the following errors:
```
[event.ThingStatusInfoEvent] - 'mqtt:systemBroker:mqtt_connection' updated: OFFLINE (COMMUNICATION_ERROR): java.net.UnknownHostException: 10.0.0.10:1883: invalid IPv6 address
[hingStatusInfoChangedEvent] - Received event of type 'ThingStatusInfoChangedEvent' under the topic 'smarthome/things/mqtt:systemBroker:mqtt_connection/statuschanged' with payload: '[{"status":"OFFLINE","statusDetail":"COMMUNICATION_ERROR","description":"java.net.UnknownHostException: 10.0.0.10:1883: invalid IPv6 address"},{"status":"OFFLINE","statusDetail":"NONE"}]'
[hingStatusInfoChangedEvent] - 'mqtt:systemBroker:mqtt_connection' changed from OFFLINE to OFFLINE (COMMUNICATION_ERROR): java.net.UnknownHostException: 10.0.0.10:1883: invalid IPv6 address
```

## Context
I'm trying to establish a MQTT connection to eclipse-mosquitto that runs via IPv4.

## Your Environment
Openhab and Mosquitto are running in two separate docker containers managed with docker-compose.
Container configs:
 ```
mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    restart: always
openhab:
    image: openhab/openhab
    environment:
      - USER_ID=997
      - GROUP_ID=996
    ports:
      - 9080:8080
      - 9443:8443
    restart: always

```
