### ISSUE TITLE
[http] buffer size overflow with larger JSON

### ISSUE THREAD

**Issue by binderth** [openhab/openhab-addons#9389]
Trying to receive a JSON from Mowas (https://warnung.bund.de/bbk.mowas/gefahrendurchsagen.json), I get the following WARN in log and the channel is still NULL:
```
2020-12-15 13:34:33.920 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'https://warnung.bund.de/bbk.mowas/gefahrendurchsagen.json' (method='GET', content='null') failed: Buffering capacity 2097152 exceeded
```
The binding doesn't seem to give me the opportunity to define the buffer size.

My Thing and channel definition:
```
UID: http:url:mowas
label: HTTP Gefahren MoWas
thingTypeUID: http:url
configuration:
  authMode: BASIC
  ignoreSSLErrors: false
  baseURL: https://warnung.bund.de/bbk.mowas/gefahrendurchsagen.json
  refresh: 600
  commandMethod: GET
  contentType: application/json
  timeout: 3000
channels:
  - id: mowasJSON
    channelTypeUID: http:string
    label: JSON von Mowas
    description: ""
    configuration: {}
```

## Expected Behavior
Having a attribute for the binding regarding buffer size if too small

## Current Behavior
Binding breaks with a WARN in the log

## Steps to Reproduce (for Bugs)
1. use the URL above as it is currently pretty big JSON response
2. see in log

## Context
I try to get the whole JSON to filter out the messages I'd like to use in OH3

## Your Environment
* OH3.RC1 on Raspberry PI 3B+
* openHABIAN 1.6
