### ISSUE TITLE
[http] Support Unit of Measurement (UoM) for Number channels

### ISSUE THREAD

**Issue by martingruening** [openhab/openhab-addons#9590]
It would be helpful to support Unit of Measurement for Number channels

**UseCase 1 - Reading data without UoM and adding it in OpenHAB**
When I'm reading the value of '577' with a GET request into a Number:Power channel that is linked to a Number:Power item
the items ends up in being in the state of '577 W'.

**UseCase 2 - Reading data with UoM and adding it in OpenHAB**
When I'm reading the value of '577mW' with a GET request into a Number:Power channel that is linked to a Number:Power item
the items ends up in being in the state of '0.577 W' (due to the automatic internal conversion from Milliwatt to Watt)

Currently I can link a Number:Power item to a Number channel and end up without the UoM being populated.

**Comment by J-N-K** [comment]
@martingruening Can you check if the linked PR is what you had in mind?

**Comment by martingruening** [comment]
By reading the source, I would say yes. But there is a lot of guessing involved as I'm not fluent in the internals of OpenHAB. If you could provide a jar as before, I will test the changes with different channels.

**Comment by J-N-K** [comment]
Same location as before: https://janessa.me/esh/org.openhab.binding.http-3.1.0-SNAPSHOT.jar

**Comment by martingruening** [comment]
Thanks. Done the testing:

This works: adding a unit to reading from the channel without a unit
This does not work: reading the unit from the channel itself

Example - HTTP GET delivers this JSON:
```
{
    "type": "INTEGER",
    "accessMode": "RO",
    "text": "Negative values for Consumption; positive for Production",
    "unit": "W",
    "value": 1211
}
```

This channel config is working as expected (adding the unit fixed in the channel config):
```
  - id: meter0ActivePower
    channelTypeUID: http:number
    label: meter0ActivePower
    description: ""
    configuration:
      mode: READONLY
      unit: W
      stateExtension: meter0/ActivePower
      stateTransformation: JSONPATH:$.value
```

What is not working is this channel config (the state transformation delivers "1211W" including the unit):
```
  - id: meter0ActivePower
    channelTypeUID: http:number
    label: meter0ActivePower
    description: ""
    configuration:
      mode: READONLY
      stateExtension: meter0/ActivePower
      stateTransformation: JSONPATH:$.concat($.value,$.unit)

```

Result:
`[WARN ] [http.internal.http.RefreshingUrlCache] - Failed processing result for URL http://kube.gruning.eu:8084/rest/channel/meter0/ActivePower: Character W is neither a decimal digit number, decimal point, nor "e" notation exponential mark`.

For me the improvement is quite helpful already. Managing the second case would be helpful whenever the unit is present in the channel output.
