### ISSUE TITLE
[wled] Discovery reports additional thing although WLED thing is already in place and working

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-addons#9642]
## Expected Behavior
After creation of a discovered WLED thing (which is online and working), I expect no discovery of an additional thing (which can't be removed or ignored, by the way)

## Current Behavior
I created a WLED thing which is working find. Still, the thing discovery detects a thing with a strange IP address.
Also this thing can't be deleted or ignored and stays in the inbox all the time

![image](https://user-images.githubusercontent.com/22266373/103457919-836afe80-4d03-11eb-9258-0b612abbe3c7.png)

![image](https://user-images.githubusercontent.com/22266373/103457930-9bdb1900-4d03-11eb-943d-3770610c41cc.png)

![image](https://user-images.githubusercontent.com/22266373/103457939-a85f7180-4d03-11eb-9c9d-cb7bfc8af12b.png)

## Possible Solution
Stop detecting a thing at a wrong IP address which doesn't exist (my net is like 192.168.1.x) 

## Steps to Reproduce (for Bugs)
1. Install WLED binding
2. Create thing
3. Check Inbox -> another thing will show up

## Context
I'm running WLED 0.9.1

## Your Environment
```
runtimeInfo:
  version: 3.1.0
  buildString: "Build #2111"
locale: de_AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 74450568
  totalMemory: 194904064
bindings:
  - amazonechocontrol
  - daikin
  - denonmarantz
  - exec
  - harmonyhub
  - http
  - ipcamera
  - mqtt
  - netatmo
  - network
  - ntp
  - systeminfo
  - unifi
  - wled
  - worxlandroid
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-US
      - en-AU
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2021-01-02T13:07:42.184Z
```
