### ISSUE TITLE
[MQTT] GUI Bug leads to Channel Updates don't follow the default rules for 'Contact'

### ISSUE THREAD

**Issue by binderth** [openhab/openhab-addons#9710]
## Expected Behavior
If I add a Channel in a `Generic MQTT Thing` and the GUI tells me default values for `Custom On/Open Value` and `Custom Off/Closed Value`, I expect the channel to follow those rules.
In that case, I expect a MQTT-message of "1" opens the channel and "0" closes the channel.

## Current Behavior
while adding a Channel in GUI, the values are prefilled with "0" and "1". I can delete them, but if I leave the input field, the default values again appear, if I leave the field empty.
After that, if a MQTT-message will be sent to the defined topic for the channel, an error will occur:
```
2021-01-06 11:43:49.100 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command '0' not supported by type 'OpenCloseValue': No enum constant org.openhab.core.library.types.OpenClosedType.0
2021-01-06 11:43:49.148 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command '1' not supported by type 'OpenCloseValue': No enum constant org.openhab.core.library.types.OpenClosedType.1
```
more information here: https://community.openhab.org/t/oh3-gui-channel-updates-mqtt-dont-follow-default-rules-for-contact/113142

## Possible Solution
add "0" and "1" as standard OFF/CLOSED ON/OPEN behaviour while dealing with MQTT-messages (or REST-API for that matter)

## Steps to Reproduce (for Bugs)
1. create a working MQTT Bridge
2. add a "generic MQTT Thing"
3. add a "Contact" channel
4. send "0" to the in the channel defined topic

## Context
Workaround is to go to "CODE" for each Contact channel and manually add the on/off values in the YAML:
```
  - id: State_AnforderungKessel1
    channelTypeUID: mqtt:contact
    label: Anforderung Kessel 1
    description: ""
    configuration:
      stateTopic: openHAB/master/Oktopus/State_AnforderungKessel1
      off: "0"
      on: "1"
```
That'll do the job.

## Your Environment
* openHAB 3.0.0 - Release Build
