### ISSUE TITLE
[mqtt] Topics not subscribed after OpenHab 3.0 restart on generic MQTT Thing

### ISSUE THREAD

**Issue by TheNetStriker** [openhab/openhab-addons#9715]
Sometimes after a restart of OpenHab 3.0 the topics of one MQTT Things are not correctly subscribed. I can send MQTT commands out from OpenHab, but updates to the topics are not reflected to the items. When this happens I can always find a specific error in the OpenHab log which seems to be related to the HomeAssistant handler, but it affects a generic MQTT Thing. Before the update to OpenHab 3.0 I did not have this problem. I've also reported this in the community forum: https://community.openhab.org/t/oh3-mqtt-somtimes-issues-after-starting/113104

When I try to disable and re-enable the generic MQTT Thing in the UI I also get the error `java.lang.ClassNotFoundException: org.slf4j.LoggerFactory` in the UI. My Things are configured via the UI and the Items with files. I have 13 MQTT Things and 2 brokers in total with a mix of Homeassistant, Homie and generic MQTT Things. The one that often fails after a restart also has a lot of channels. (69 in total) I've also created [this issue](https://github.com/openhab/openhab-addons/issues/9711) about a different warning that I get after every start regarding an HomeAssistant (ESPHome) Thing.

The only way to solve the problem at the moment is to restart OpenHab again, maybe even twice until the error in the log does not appear anymore. Below you can see the log and the Thing config of the generic Thing with a lot of channels.

## OpenHab Log
```
2021-01-05 23:34:39.028 [WARN ] [org.openhab.core.internal.common.WrappedScheduledExecutorService                                    ] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: null
        at org.openhab.binding.mqtt.generic.MqttChannelTypeProvider.derive(MqttChannelTypeProvider.java:132) ~[?:?]
        at org.openhab.binding.mqtt.homeassistant.internal.discovery.HomeAssistantDiscovery.publishResults(HomeAssistantDiscovery.java:197) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
## Generic MQTT Thing config
```
UID: mqtt:topic:zigbee2mqtt_local
label: zigbee2mqtt lokal
thingTypeUID: mqtt:topic
configuration: {}
bridgeUID: mqtt:broker:4ce1d806
location: System
channels:
  - id: group_all_color
    channelTypeUID: mqtt:colorHSB
    label: Gruppe Alle Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/group_all/set
      stateTopic: zigbee2mqtt/group_all
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: group_pc_color
    channelTypeUID: mqtt:colorHSB
    label: Gruppe PC Zimmer Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/group_pc/set
      stateTopic: zigbee2mqtt/group_pc
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: group_kitchen_color
    channelTypeUID: mqtt:colorHSB
    label: Gruppe Küche Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/group_kitchen/set
      stateTopic: zigbee2mqtt/group_kitchen
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: group_bedroom_color
    channelTypeUID: mqtt:colorHSB
    label: Gruppe Schlafzimmer Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/group_bedroom/set
      stateTopic: zigbee2mqtt/group_bedroom
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: group_bathroom_color
    channelTypeUID: mqtt:colorHSB
    label: Gruppe Badezimmer Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/group_bathroom/set
      stateTopic: zigbee2mqtt/group_bathroom
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: group_livingroom_color
    channelTypeUID: mqtt:colorHSB
    label: Gruppe Wohnzimmer Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/group_livingroom/set
      stateTopic: zigbee2mqtt/group_livingroom
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: group_livingroom_front_color
    channelTypeUID: mqtt:colorHSB
    label: Gruppe Wohnzimmer vorne Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/group_livingroom_front/set
      stateTopic: zigbee2mqtt/group_livingroom_front
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: group_livingroom_back_color
    channelTypeUID: mqtt:colorHSB
    label: Gruppe Wohnzimmer hinten Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/group_livingroom_back/set
      stateTopic: zigbee2mqtt/group_livingroom_back
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: group_livingroom_standing_color
    channelTypeUID: mqtt:colorHSB
    label: Gruppe Wohnzimmer Stehlampen Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/group_livingroom_standing/set
      stateTopic: zigbee2mqtt/group_livingroom_standing
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: pc_1_color
    channelTypeUID: mqtt:colorHSB
    label: PC Zimmer 1 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/pc_1/set
      stateTopic: zigbee2mqtt/pc_1
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: pc_1_temperature
    channelTypeUID: mqtt:dimmer
    label: PC Zimmer 1 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/pc_1/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/pc_1
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: pc_2_color
    channelTypeUID: mqtt:colorHSB
    label: PC Zimmer 2 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/pc_2/set
      stateTopic: zigbee2mqtt/pc_2
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: pc_2_temperature
    channelTypeUID: mqtt:dimmer
    label: PC Zimmer 2 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/pc_2/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/pc_2
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: pc_3_color
    channelTypeUID: mqtt:colorHSB
    label: PC Zimmer 3 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/pc_3/set
      stateTopic: zigbee2mqtt/pc_3
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: pc_3_temperature
    channelTypeUID: mqtt:dimmer
    label: PC Zimmer 3 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/pc_3/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/pc_3
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: pc_4_color
    channelTypeUID: mqtt:colorHSB
    label: PC Zimmer 4 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/pc_4/set
      stateTopic: zigbee2mqtt/pc_4
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: pc_4_temperature
    channelTypeUID: mqtt:dimmer
    label: PC Zimmer 4 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/pc_4/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/pc_4
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: kitchen_1_color
    channelTypeUID: mqtt:colorHSB
    label: Küche 1 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/kitchen_1/set
      stateTopic: zigbee2mqtt/kitchen_1
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: kitchen_1_temperature
    channelTypeUID: mqtt:dimmer
    label: Küche 1 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/kitchen_1/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/kitchen_1
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: kitchen_2_color
    channelTypeUID: mqtt:colorHSB
    label: Küche 2 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/kitchen_2/set
      stateTopic: zigbee2mqtt/kitchen_2
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: kitchen_2_temperature
    channelTypeUID: mqtt:dimmer
    label: Küche 2 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/kitchen_2/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/kitchen_2
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: kitchen_3_color
    channelTypeUID: mqtt:colorHSB
    label: Küche 3 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/kitchen_3/set
      stateTopic: zigbee2mqtt/kitchen_3
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: kitchen_3_temperature
    channelTypeUID: mqtt:dimmer
    label: Küche 3 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/kitchen_3/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/kitchen_3
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: kitchen_4_color
    channelTypeUID: mqtt:colorHSB
    label: Küche 4 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/kitchen_4/set
      stateTopic: zigbee2mqtt/kitchen_4
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: kitchen_4_temperature
    channelTypeUID: mqtt:dimmer
    label: Küche 4 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/kitchen_4/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/kitchen_4
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: kitchen_5_color
    channelTypeUID: mqtt:colorHSB
    label: Küche 5 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/kitchen_5/set
      stateTopic: zigbee2mqtt/kitchen_5
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: kitchen_5_temperature
    channelTypeUID: mqtt:dimmer
    label: Küche 5 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/kitchen_5/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/kitchen_5
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: kitchen_bar_color
    channelTypeUID: mqtt:colorHSB
    label: Küche Bar Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/kitchen_bar/set
      stateTopic: zigbee2mqtt/kitchen_bar
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: bedroom_1_color
    channelTypeUID: mqtt:colorHSB
    label: Schlafzimmer 1 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/bedroom_1/set
      stateTopic: zigbee2mqtt/bedroom_1
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: bedroom_1_temperature
    channelTypeUID: mqtt:dimmer
    label: Schlafzimmer 1 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/bedroom_1/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/bedroom_1
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: bedroom_2_color
    channelTypeUID: mqtt:colorHSB
    label: Schlafzimmer 2 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/bedroom_2/set
      stateTopic: zigbee2mqtt/bedroom_2
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: bedroom_2_temperature
    channelTypeUID: mqtt:dimmer
    label: Schlafzimmer 2 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/bedroom_2/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/bedroom_2
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: bedroom_3_color
    channelTypeUID: mqtt:colorHSB
    label: Schlafzimmer 3 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/bedroom_3/set
      stateTopic: zigbee2mqtt/bedroom_3
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: bedroom_3_temperature
    channelTypeUID: mqtt:dimmer
    label: Schlafzimmer 3 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/bedroom_3/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/bedroom_3
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: bedroom_4_color
    channelTypeUID: mqtt:colorHSB
    label: Schlafzimmer 4 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/bedroom_4/set
      stateTopic: zigbee2mqtt/bedroom_4
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: bedroom_4_temperature
    channelTypeUID: mqtt:dimmer
    label: Schlafzimmer 4 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/bedroom_4/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/bedroom_4
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: bedroom_5_color
    channelTypeUID: mqtt:colorHSB
    label: Schlafzimmer 5 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/bedroom_5/set
      stateTopic: zigbee2mqtt/bedroom_5
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: bedroom_5_temperature
    channelTypeUID: mqtt:dimmer
    label: Schlafzimmer 5 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/bedroom_5/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/bedroom_5
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: bedroom_6_color
    channelTypeUID: mqtt:colorHSB
    label: Schlafzimmer 6 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/bedroom_6/set
      stateTopic: zigbee2mqtt/bedroom_6
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: bedroom_6_temperature
    channelTypeUID: mqtt:dimmer
    label: Schlafzimmer 6 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/bedroom_6/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/bedroom_6
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: bedroom_table_color
    channelTypeUID: mqtt:colorHSB
    label: Schlafzimmer Nachttisch Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/bedroom_table/set
      stateTopic: zigbee2mqtt/bedroom_table
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_front_1_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer vorne 1 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_front_1/set
      stateTopic: zigbee2mqtt/livingroom_front_1
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_front_1_temperature
    channelTypeUID: mqtt:dimmer
    label: Wohnzimmer vorne 1 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/livingroom_front_1/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/livingroom_front_1
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: livingroom_front_2_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer vorne 2 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_front_2/set
      stateTopic: zigbee2mqtt/livingroom_front_2
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_front_2_temperature
    channelTypeUID: mqtt:dimmer
    label: Wohnzimmer vorne 2 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/livingroom_front_2/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/livingroom_front_2
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: livingroom_front_3_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer vorne 3 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_front_3/set
      stateTopic: zigbee2mqtt/livingroom_front_3
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_front_3_temperature
    channelTypeUID: mqtt:dimmer
    label: Wohnzimmer vorne 3 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/livingroom_front_3/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/livingroom_front_3
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: livingroom_front_top_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer vorne oben Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_front_top/set
      stateTopic: zigbee2mqtt/livingroom_front_top
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_front_top_temperature
    channelTypeUID: mqtt:dimmer
    label: Wohnzimmer vorne oben Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/livingroom_front_top/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/livingroom_front_top
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: livingroom_front_left_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer vorne links Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_front_left/set
      stateTopic: zigbee2mqtt/livingroom_front_left
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_front_right_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer vorne rechts Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_front_right/set
      stateTopic: zigbee2mqtt/livingroom_front_right
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_back_1_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer hinten 1 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_back_1/set
      stateTopic: zigbee2mqtt/livingroom_back_1
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_back_1_temperature
    channelTypeUID: mqtt:dimmer
    label: Wohnzimmer hinten 1 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/livingroom_back_1/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/livingroom_back_1
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: livingroom_back_2_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer hinten 2 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_back_2/set
      stateTopic: zigbee2mqtt/livingroom_back_2
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_back_2_temperature
    channelTypeUID: mqtt:dimmer
    label: Wohnzimmer hinten 2 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/livingroom_back_2/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/livingroom_back_2
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: livingroom_back_3_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer hinten 3 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_back_3/set
      stateTopic: zigbee2mqtt/livingroom_back_3
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_back_3_temperature
    channelTypeUID: mqtt:dimmer
    label: Wohnzimmer hinten 3 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/livingroom_back_3/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/livingroom_back_3
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: livingroom_back_top_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer hinten oben Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_back_top/set
      stateTopic: zigbee2mqtt/livingroom_back_top
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_back_top_temperature
    channelTypeUID: mqtt:dimmer
    label: Wohnzimmer hinten oben Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/livingroom_back_top/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/livingroom_back_top
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: livingroom_back_left_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer hinten links Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_back_left/set
      stateTopic: zigbee2mqtt/livingroom_back_left
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: livingroom_back_right_color
    channelTypeUID: mqtt:colorHSB
    label: Wohnzimmer hinten rechts Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/livingroom_back_right/set
      stateTopic: zigbee2mqtt/livingroom_back_right
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: bathroom_1_color
    channelTypeUID: mqtt:colorHSB
    label: Badezimmer 1 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/bathroom_1/set
      stateTopic: zigbee2mqtt/bathroom_1
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: bathroom_1_temperature
    channelTypeUID: mqtt:dimmer
    label: Badezimmer 1 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/bathroom_1/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/bathroom_1
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: bathroom_2_color
    channelTypeUID: mqtt:colorHSB
    label: Badezimmer 2 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/bathroom_2/set
      stateTopic: zigbee2mqtt/bathroom_2
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: bathroom_2_temperature
    channelTypeUID: mqtt:dimmer
    label: Badezimmer 2 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/bathroom_2/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/bathroom_2
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: bathroom_3_color
    channelTypeUID: mqtt:colorHSB
    label: Badezimmer 3 Farbe
    description: null
    configuration:
      transformationPatternOut: JS:zigbee2mqtt_color_to_json.js
      commandTopic: zigbee2mqtt/bathroom_3/set
      stateTopic: zigbee2mqtt/bathroom_3
      transformationPattern: JS:zigbee2mqtt_json_to_color.js
      off: 42,46,0
      onBrightness: 100
      on: 42,46,100
  - id: bathroom_3_temperature
    channelTypeUID: mqtt:dimmer
    label: Badezimmer 3 Temperatur
    description: null
    configuration:
      commandTopic: zigbee2mqtt/bathroom_3/set
      transformationPatternOut: JS:zigbee2mqtt_dimmer_to_temp.js
      stateTopic: zigbee2mqtt/bathroom_3
      transformationPattern: JS:zigbee2mqtt_temp_to_dimmer.js
  - id: huetap_1
    channelTypeUID: mqtt:string
    label: Hue Tap 1
    description: null
    configuration:
      stateTopic: zigbee2mqtt/huetap_1
      transformationPattern: JSONPATH:$.action
  - id: huetap_2
    channelTypeUID: mqtt:string
    label: Hue Tap 2
    description: null
    configuration:
      stateTopic: zigbee2mqtt/huetap_2
      transformationPattern: JSONPATH:$.action
```
## Your Environment
OpenHab 3.0 running on Rasperry Pi 4 (OpenHabian)

I hope those infos are sufficient to analyze the problem.
