### ISSUE TITLE
[mqtt.homie] Binding subscribes/publishes with QoS 0 although openHAB setting is different

### ISSUE THREAD

**Issue by stedon81** [openhab/openhab-addons#9919]
## Expected Behavior
The binding should subscribe at the broker with the QoS level defined in the MQTT-Broker-Thing's settings.
If the binding connects to the broker and subscribes for the channels of a homie thing, it should specify the QoS level defined by the user.
Likewise, the binding should publish messages to the broker with the QoS level defined in the MQTT-Broker settings.

## Current Behavior
If the binding connects to the broker and subscribes for the channels of a homie thing, it always subscribes with QoS 0, although my settings in openHAB say that QoS 2 should be used.

DEBUG log from mosquitto broker:
```
1611354225: Received SUBSCRIBE from openHAB
1611354225:     homie/T_KG_Tuer_Fingerabdrucksensor/fingerprint/touch (QoS 0)
1611354225: openHAB 0 homie/T_KG_Tuer_Fingerabdrucksensor/fingerprint/touch
1611354225: Sending SUBACK to openHAB
1611354225: Sending PUBLISH to openHAB (d0, q0, r1, m0, 'homie/T_KG_Tuer_Fingerabdrucksensor/fingerprint/touch', ... (5 bytes))
```
Also, if the binding publishes a value to the broker, it publishes it with QoS 0:

```
Received PUBLISH from openHAB (d0, q0, r0, m0, 'homie/T_KG_Tuer_Fingerabdrucksensor/bell/response/set', ... (1 bytes))
```

Broker thing configuration:
```
UID: mqtt:broker:mosquitto
label: GTW_Mosquitto
thingTypeUID: mqtt:broker
configuration:
  publickeypin: false
  lwtQos: 1
  lastwill_qos: 1
  clientid: ce05f2fc-7936-4193-ab5a-f5e87258aa60
  keepAlive: 60
  clientID: openHAB
  retain: true
  secure: false
  certificatepin: false
  keep_alive_time: 60000
  password: *****************
  qos: 2
  reconnectTime: 60000
  port: 1884
  host: 127.0.0.1
  lwtRetain: true
  reconnect_time: 60000
  username: ****************
  enableDiscovery: true
```

## Possible Solution
No idea. Seems strange, because `createBrokerConnection` sets the QoS from configuration in the connection object.
Connection's `subscribeRaw` passes the qos to the mqttClient.
Suspicion:
In `Mqtt3AsyncClientWrapper.subscribe` as well as in `Mqtt3AsyncClientWrapper.publish`, a function `getMqttQosFromInt` tries to convert the `int` parameter `qos` to an enum. This function returns the wrong QoS enum values for qos==0 and qos==1, but the correct one for qos==2. So this also is a red herring. I can't explain to myself why the broker only sees requests for QoS 0.

## Your Environment
* Version used: openHABian 3.0.0-release
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Debian
