### ISSUE TITLE
[Tr064] wanIP Address SOAP Fault 401 (Still some Warnings in OH log)

### ISSUE THREAD

**Issue by WhiteSockedDancer** [openhab/openhab-addons#9978]
I'm still getting the Warnings for 2 Channels in the WAN Subdevice. 
Similar to the Issue #9173 

Uptime and connection status.
I don't have any items linked to this subdevice-thing.

I've got a
FRITZ!Box 7490
Software Version 113.07.21

![image](https://user-images.githubusercontent.com/52671054/106173617-6a375f80-6194-11eb-9c50-35d6153fa891.png)

I created the main device more or less a month ago.
I just recreated this subdevice today.
Do i need to create the whole Device and all subdevices to get rid of this warning?
Or is this warning probably wanted since i use ppp for the WAN connection?

LG Jay

**Comment by J-N-K** [comment]
Please show thing config.

**Comment by WhiteSockedDancer** [comment]
Main Device (deleted pw):
```
UID: tr064:fritzbox:Router
label: Router
thingTypeUID: tr064:fritzbox
configuration:
  phonebookInterval: 0
  host: 192.168.1.1
  refresh: 60
  password: 
  user: openhab
```

WAN subdevice:
```
UID: tr064:subdevice:Router:WAN
label: Router - WAN
thingTypeUID: tr064:subdevice
configuration:
  refresh: 60
  uuid: uuid:75802409-bccb-40e7-8e69-C80E14704A44
bridgeUID: tr064:fritzbox:Router
```

LAN subdevice:
```
UID: tr064:subdevice:Router:LAN
label: Router - LAN
thingTypeUID: tr064:subdevice
configuration:
  refresh: 60
  uuid: uuid:75802409-bccb-40e7-8e6b-C80E14704A44
bridgeUID: tr064:fritzbox:Router
```

DSL subdevice:
```
UID: tr064:subdevice:Router:DSL
label: Router - DSL
thingTypeUID: tr064:subdevice
configuration:
  refresh: 60
  uuid: uuid:75802409-bccb-40e7-8e6a-C80E14704A44
bridgeUID: tr064:fritzbox:Router
```
